;"><svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3 6h18"/><path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2"/><path d="M19 6l-1 14c-.1 1.1-1 2-2.1 2H8.1C7 22 6.1 21.1 6 20L5 6"/><path d="M10 11v6"/><path d="M14 11v6"/></svg></span>`;
const freeImageHtml=(src:string)=>`<span class="planner-free-image" contenteditable="false" data-selected="true" style="position:absolute;left:16px;top:16px;width:45%;max-width:calc(100% - 32px);display:block;z-index:2;touch-action:none;user-select:none;"><img src="${src}" alt="Imagen" draggable="false" style="display:block;width:100%;height:auto;border-radius:10px;pointer-events:auto;"/>${deleteHandle}${handle("nw")}${handle("ne")}${handle("sw")}${handle("se")}</span>`;
function upgradeImages(root:HTMLElement){root.querySelectorAll<HTMLElement>(".planner-free-image").forEach(w=>{const oldDelete=w.querySelector<HTMLElement>(".free-image-delete");if(oldDelete){const temp=document.createElement("div");temp.innerHTML=deleteHandle;oldDelete.replaceWith(temp.firstElementChild!)}else w.insertAdjacentHTML("afterbegin",deleteHandle)});root.querySelectorAll<HTMLImageElement>("img").forEach(img=>{if(img.closest(".planner-free-image"))return;const wrap=document.createElement("span");wrap.innerHTML=freeImageHtml(img.src);img.replaceWith(wrap.firstElementChild!);});}
function ensureRootHeight(root:HTMLElement){let bottom=192;root.querySelectorAll<HTMLElement>(".planner-free-image").forEach(w=>{const top=parseFloat(w.style.top)||0;const width=w.getBoundingClientRect().width||parseFloat(w.style.width)||120;const img=w.querySelector("img") as HTMLImageElement|null;const ratio=img?.naturalWidth&&img?.naturalHeight?img.naturalWidth/img.naturalHeight:1;bottom=Math.max(bottom,top+width/Math.max(ratio,.1)+28)});root.style.minHeight=`${Math.ceil(bottom)}px`;}
function deselectAllImages(except?:HTMLElement){document.querySelectorAll<HTMLElement>(".planner-free-image, .planner-flex-free-image").forEach(w=>{if(w!==except)w.dataset.selected="false"})}
function applyInlineStyle(range:Range,styles:Record<string,string>){if(range.collapsed)return;try{const common=range.commonAncestorContainer.nodeType===Node.ELEMENT_NODE?range.commonAncestorContainer as HTMLElement:range.commonAncestorContainer.parentElement;const selectedText=range.toString();const candidate=common?.closest<HTMLElement>('span[data-planner-stroke="1"], span');if(candidate&&candidate.textContent===selectedText){if("WebkitTextStroke" in styles)candidate.dataset.plannerStroke="1";Object.assign(candidate.style,styles);const next=document.createRange();next.selectNodeContents(candidate);const sel=window.getSelection();sel?.removeAllRanges();sel?.addRange(next);return}const span=document.createElement("span");Object.assign(span.style,styles);const fragment=range.extractContents();if("WebkitTextStroke" in styles){span.dataset.plannerStroke="1";fragment.querySelectorAll?.("*").forEach((node:any)=>{if(node?.style){node.style.webkitTextStroke="";node.style.setProperty("-webkit-text-stroke","");node.style.paintOrder=""}if(node?.dataset?.plannerStroke)delete node.dataset.plannerStroke})}span.appendChild(fragment);range.insertNode(span);const next=document.createRange();next.selectNodeContents(span);const sel=window.getSelection();sel?.removeAllRanges();sel?.addRange(next)}catch{/* keep editor usable if browser rejects a complex range */}}

function NotasPage(){
 const refs=useRef<Record<BoxId,HTMLDivElement|null>>({hoy:null,libre:null}); const inkCanvasRefs=useRef<Record<BoxId,HTMLCanvasElement|null>>({hoy:null,libre:null}); const inkDrawingRef=useRef<{id:BoxId;last:{x:number;y:number}|null}|null>(null); const inkUndoRef=useRef<Record<BoxId,string[]>>({hoy:[],libre:[]}); const inkRedoRef=useRef<Record<BoxId,string[]>>({hoy:[],libre:[]}); const textUndoRef=useRef<Record<BoxId,string[]>>({hoy:[],libre:[]}); const textRedoRef=useRef<Record<BoxId,string[]>>({hoy:[],libre:[]}); const fileRef=useRef<HTMLInputElement>(null); const selectionRef=useRef<Range|null>(null); const transformRef=useRef<{box:BoxId;wrap:HTMLElement;root:HTMLElement;mode:"move"|"resize";corner:string;x:number;y:number;left:number;top:number;width:number;ratio:number}|null>(null); const [active,setActive]=useState<BoxId>("hoy"); const [panel,setPanel]=useState<Panel>(null); const [group,setGroup]=useState<StickerGroup>("Favoritos"); const [copied,setCopied]=useState(""); const [font,setFont]=useState("Arial"); const [fontSize,setFontSize]=useState("3"); const [shadow,setShadow]=useState("0"); const [strokeWidth,setStrokeWidth]=useState("0"); const [strokeColor,setStrokeColor]=useState("#111111"); const [backgrounds,setBackgrounds]=useState<Record<BoxId,string>>({hoy:"#FFFFFF",libre:"#FFFFFF"}); const [backgroundExpanded,setBackgroundExpanded]=useState(false); const [inkTool,setInkTool]=useState<"off"|"pen"|"eraser">("off"); const [inkColor,setInkColor]=useState(()=>localStorage.getItem("planner-ink-color")||"#65475F"); const [inkWidth,setInkWidth]=useState(()=>{const n=Number(localStorage.getItem("planner-ink-width")||4);return Number.isFinite(n)?Math.min(12,Math.max(2,n)):4}); const [inkRecognizing,setInkRecognizing]=useState(false); const [inkMore,setInkMore]=useState(false);
 useEffect(()=>{localStorage.setItem("planner-ink-color",inkColor)},[inkColor]);
 useEffect(()=>{localStorage.setItem("planner-ink-width",String(inkWidth))},[inkWidth]);
 useEffect(()=>{const next={hoy:localStorage.getItem("planner-box-background-hoy")||"#FFFFFF",libre:localStorage.getItem("planner-box-background-libre")||"#FFFFFF"};setBackgrounds(next);BOXES.forEach(({id})=>{const el=refs.current[id];if(el){el.innerHTML=localStorage.getItem(storageKey(id))??"";upgradeImages(el);ensureRootHeight(el);localStorage.setItem(storageKey(id),el.innerHTML)}})},[]);
 useEffect(()=>{const onTouchStart=(e:TouchEvent)=>{const t=e.target as HTMLElement;if(t.closest(".planner-free-image, .planner-flex-free-image"))e.preventDefault()};document.addEventListener("touchstart",onTouchStart,{passive:false});return()=>document.removeEventListener("touchstart",onTouchStart)},[]);
 useEffect(()=>{const onSelectionChange=()=>{const sel=window.getSelection();if(!sel||!sel.rangeCount||sel.isCollapsed)return;const r=sel.getRangeAt(0);for(const id of ["hoy","libre"] as BoxId[]){const root=refs.current[id];if(root&&root.contains(r.startContainer)&&root.contains(r.endContainer)){delete document.body.dataset.activeFlexNoteId;setActive(id);selectionRef.current=r.cloneRange();break}}};document.addEventListener("selectionchange",onSelectionChange);return()=>document.removeEventListener("selectionchange",onSelectionChange)},[]);
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(e.key!=="Delete"&&e.key!=="Backspace")return;const sel=document.querySelector<HTMLElement>('.planner-free-image[data-selected="true"],.planner-flex-free-image[data-selected="true"]');if(!sel)return;e.preventDefault();if(sel.classList.contains("planner-flex-free-image")){window.dispatchEvent(new CustomEvent("planner:flex-remove-selected"));return}const root=sel.closest<HTMLElement>("[contenteditable]");sel.remove();if(root){ensureRootHeight(root);const box=(Object.keys(refs.current) as BoxId[]).find(k=>refs.current[k]===root);if(box)save(box)}};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[]);
 useEffect(()=>{const onBaseAdd=(ev:Event)=>{const e=ev as CustomEvent<{box:BoxId;src:string;left?:number;top?:number}>;const{box,src,left,top}=e.detail||({} as {box?:BoxId;src?:string;left?:number;top?:number});if(!box||!src)return;const root=refs.current[box];if(!root)return;root.insertAdjacentHTML("beforeend",freeImageHtml(src));if(left!==undefined||top!==undefined){const inserted=root.lastElementChild as HTMLElement|null;if(inserted){if(left!==undefined)inserted.style.left=`${Math.max(0,left)}px`;if(top!==undefined)inserted.style.top=`${Math.max(0,top)}px`}}upgradeImages(root);ensureRootHeight(root);save(box)};window.addEventListener("planner:base-add-image",onBaseAdd as EventListener);return()=>window.removeEventListener("planner:base-add-image",onBaseAdd as EventListener)},[]);
 const pushTextUndo=(id:BoxId=active)=>{const el=refs.current[id];if(!el)return;const html=el.innerHTML,stack=textUndoRef.current[id];if(stack[stack.length-1]!==html)stack.push(html);if(stack.length>50)stack.shift();textRedoRef.current[id]=[]};
 const restoreText=(id:BoxId,html:string)=>{const el=refs.current[id];if(!el)return;el.innerHTML=html;upgradeImages(el);ensureRootHeight(el);localStorage.setItem(storageKey(id),html)};
 const undoText=(id:BoxId=active)=>{const el=refs.current[id],stack=textUndoRef.current[id];if(!el||!stack.length)return;textRedoRef.current[id].push(el.innerHTML);restoreText(id,stack.pop()||"")};
 const redoText=(id:BoxId=active)=>{const el=refs.current[id],stack=textRedoRef.current[id];if(!el||!stack.length)return;textUndoRef.current[id].push(el.innerHTML);restoreText(id,stack.pop()||"")};
 const save=(id:BoxId)=>{const el=refs.current[id];if(el)localStorage.setItem(storageKey(id),el.innerHTML)}; const remember=(id:BoxId=active)=>{const s=window.getSelection(),root=refs.current[id];if(s&&s.rangeCount&&root?.contains(s.getRangeAt(0).startContainer)&&root.contains(s.getRangeAt(0).endContainer))selectionRef.current=s.getRangeAt(0).cloneRange()}; const focus=()=>{refs.current[active]?.focus({preventScroll:true});const r=selectionRef.current,s=window.getSelection();if(r&&s){s.removeAllRanges();s.addRange(r)}}; const cmd=(c:string,v?:string)=>{const flexId=document.body.dataset.activeFlexNoteId;if(flexId){window.dispatchEvent(new CustomEvent("planner:flex-format",{detail:{command:c,value:v}}));return;}pushTextUndo(active);focus();const r=selectionRef.current;if(c==="textShadow"&&r){const n=Number(v||0);applyInlineStyle(r,{textShadow:n?`0 ${n}px ${Math.max(1,n*2)}px rgba(0,0,0,.45)`:"none"})}else if(c==="textStroke"&&r){const n=Number(v||0);applyInlineStyle(r,{WebkitTextStroke:n?`${n}px ${strokeColor}`:"0 transparent",paintOrder:"stroke fill"})}else if(c==="strokeColor"){const nextColor=v||"#111111";setStrokeColor(nextColor);if(r){applyInlineStyle(r,{WebkitTextStroke:Number(strokeWidth)?`${strokeWidth}px ${nextColor}`:"0 transparent",paintOrder:"stroke fill"});requestAnimationFrame(()=>{const sel=window.getSelection();const node=sel?.anchorNode;const el=(node?.nodeType===Node.ELEMENT_NODE?node:(node?.parentElement)) as HTMLElement|null;const strokeEl=el?.closest<HTMLElement>('span[data-planner-stroke="1"]');if(strokeEl){strokeEl.style.setProperty("-webkit-text-stroke",Number(strokeWidth)?`${strokeWidth}px ${nextColor}`:"0 transparent");strokeEl.style.paintOrder="stroke fill";save(active)}})}}else document.execCommand(c,false,v);remember(active);save(active)};
 const inkKey=(id:BoxId)=>`planner-note-ink-${id}-v2`;
 const inkSnapshot=(id:BoxId)=>inkCanvasRefs.current[id]?.toDataURL("image/png")||"";
 const inkRestore=(id:BoxId,data:string)=>{const c=inkCanvasRefs.current[id];if(!c)return;const ctx=c.getContext("2d");if(!ctx)return;ctx.clearRect(0,0,c.width,c.height);if(!data)return;const img=new Image();img.onload=()=>{ctx.clearRect(0,0,c.width,c.height);ctx.drawImage(img,0,0)};img.src=data};
 const sizeInkCanvas=(id:BoxId,c:HTMLCanvasElement|null)=>{if(!c)return;inkCanvasRefs.current[id]=c;const host=c.parentElement,root=refs.current[id];if(!host||!root)return;const cssW=Math.max(1,host.clientWidth),cssH=Math.max(420,root.scrollHeight,host.clientHeight);const dpr=Math.max(1,window.devicePixelRatio||1),w=Math.round(cssW*dpr),h=Math.round(cssH*dpr);if(c.width===w&&c.height===h)return;const old=c.width?c.toDataURL("image/png"):localStorage.getItem(inkKey(id));const oldW=c.width,oldH=c.height;c.width=w;c.height=h;c.style.width=`${cssW}px`;c.style.height=`${cssH}px`;if(old){const img=new Image();img.onload=()=>{const ctx=c.getContext("2d");if(!ctx)return;ctx.clearRect(0,0,w,h);if(oldW&&oldH)ctx.drawImage(img,0,0,oldW,oldH);else ctx.drawImage(img,0,0)};img.src=old}};
 const pushInkUndo=(id:BoxId)=>{const s=inkSnapshot(id);inkUndoRef.current[id].push(s);if(inkUndoRef.current[id].length>40)inkUndoRef.current[id].shift();inkRedoRef.current[id]=[]};
 const inkPos=(id:BoxId,e:React.PointerEvent<HTMLCanvasElement>)=>{const c=inkCanvasRefs.current[id]!;const r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*(c.width/r.width),y:(e.clientY-r.top)*(c.height/r.height)}};
 const startInk=(id:BoxId,e:React.PointerEvent<HTMLCanvasElement>)=>{if(inkTool==="off")return;const c=inkCanvasRefs.current[id];if(!c)return;pushInkUndo(id);inkDrawingRef.current={id,last:inkPos(id,e)};c.setPointerCapture?.(e.pointerId)};
 const moveInk=(id:BoxId,e:React.PointerEvent<HTMLCanvasElement>)=>{const d=inkDrawingRef.current,c=inkCanvasRefs.current[id];if(!d||d.id!==id||!d.last||!c||inkTool==="off")return;const p=inkPos(id,e),ctx=c.getContext("2d");if(!ctx)return;const scale=c.width/c.getBoundingClientRect().width;ctx.lineCap="round";ctx.lineJoin="round";ctx.lineWidth=(inkTool==="eraser"?Math.max(14,inkWidth*3):inkWidth)*scale;ctx.globalCompositeOperation=inkTool==="eraser"?"destination-out":"source-over";ctx.strokeStyle=inkColor;ctx.beginPath();ctx.moveTo(d.last.x,d.last.y);ctx.lineTo(p.x,p.y);ctx.stroke();d.last=p};
 const endInk=(id:BoxId)=>{if(inkDrawingRef.current?.id===id)inkDrawingRef.current=null;const s=inkSnapshot(id);if(s)localStorage.setItem(inkKey(id),s)};
 const undoInk=(id:BoxId=active)=>{const u=inkUndoRef.current[id];if(!u.length)return;inkRedoRef.current[id].push(inkSnapshot(id));const s=u.pop()||"";inkRestore(id,s);localStorage.setItem(inkKey(id),s)};
 const redoInk=(id:BoxId=active)=>{const r=inkRedoRef.current[id];if(!r.length)return;inkUndoRef.current[id].push(inkSnapshot(id));const s=r.pop()||"";inkRestore(id,s);localStorage.setItem(inkKey(id),s)};
 const clearInk=(id:BoxId=active)=>{const c=inkCanvasRefs.current[id];if(!c)return;pushInkUndo(id);c.getContext("2d")?.clearRect(0,0,c.width,c.height);localStorage.removeItem(inkKey(id))};
 const prepareInkOcr=(source:HTMLCanvasElement)=>{const ctx=source.getContext("2d");if(!ctx)return null;const im=ctx.getImageData(0,0,source.width,source.height);let minX=source.width,minY=source.height,maxX=-1,maxY=-1;for(let y=0;y<source.height;y++)for(let x=0;x<source.width;x++){if(im.data[(y*source.width+x)*4+3]>20){minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y)}}if(maxX<0)return null;const m=30;minX=Math.max(0,minX-m);minY=Math.max(0,minY-m);maxX=Math.min(source.width-1,maxX+m);maxY=Math.min(source.height-1,maxY+m);const w=maxX-minX+1,h=maxY-minY+1,o=document.createElement("canvas");o.width=w;o.height=h;const ox=o.getContext("2d")!;ox.fillStyle="#fff";ox.fillRect(0,0,w,h);ox.drawImage(source,minX,minY,w,h,0,0,w,h);return o};
 const convertInkToText=async()=>{const c=inkCanvasRefs.current[active];if(!c)return;const prepared=prepareInkOcr(c);if(!prepared){alert("Primero escribí algo con el lápiz.");return}setInkRecognizing(true);try{const mod=await import(/* @vite-ignore */ "https://cdn.jsdelivr.net/npm/tesseract.js@6/+esm");const worker=await mod.createWorker("spa");const res=await worker.recognize(prepared.toDataURL("image/png"));await worker.terminate();const txt=String(res?.data?.text||"").replace(/\s+/g," ").trim();if(!txt){alert("No pude reconocer la escritura. Probá con letras un poco más separadas.");return}const root=refs.current[active];if(root){pushTextUndo(active);root.focus({preventScroll:true});root.append(document.createTextNode((root.innerText.trim()?" ":"")+txt));save(active)}clearInk(active);inkUndoRef.current[active]=[];inkRedoRef.current[active]=[];setInkTool("off");setInkMore(false);setPanel(null)}catch(err){console.warn(err);alert("No se pudo convertir ahora. Revisá la conexión e intentá nuevamente.")}finally{setInkRecognizing(false)}};
 const selectBase=(id:BoxId)=>{delete document.body.dataset.activeFlexNoteId;setActive(id)};
 const addImage=(file?:File)=>{if(!file)return;const r=new FileReader();r.onload=()=>{const src=String(r.result);const flexId=document.body.dataset.activeFlexNoteId;if(flexId){window.dispatchEvent(new CustomEvent("planner:flex-add-image",{detail:{noteId:flexId,src}}));return;}const root=refs.current[active];if(!root)return;deselectAllImages();root.insertAdjacentHTML("beforeend",freeImageHtml(src));ensureRootHeight(root);save(active)};r.readAsDataURL(file)};
 const startImageTransform=(box:BoxId,e:React.PointerEvent<HTMLDivElement>)=>{const target=e.target as HTMLElement;const wrap=target.closest<HTMLElement>(".planner-free-image");const root=refs.current[box];if(!wrap||!root){deselectAllImages();return;}selectBase(box);const prev=transformRef.current;if(prev){prev.root.closest<HTMLElement>(".planner-box-libre")?.classList.remove("planner-box-dragging");prev.wrap.style.zIndex="";prev.wrap.style.filter="";prev.wrap.style.opacity="";ensureRootHeight(prev.root);save(prev.box);transformRef.current=null}e.preventDefault();e.stopPropagation();if(target.dataset.action==="delete"){wrap.remove();ensureRootHeight(root);save(box);return;}deselectAllImages(wrap);wrap.dataset.selected="true";const rect=wrap.getBoundingClientRect(),img=wrap.querySelector("img") as HTMLImageElement|null;const mode=target.dataset.resize?"resize":"move";if(mode==="move"){root.closest<HTMLElement>(".planner-box-libre")?.classList.add("planner-box-dragging");wrap.style.zIndex="25";wrap.style.filter="drop-shadow(0 8px 16px rgba(0,0,0,.35))";wrap.style.opacity="0.92"}transformRef.current={box,wrap,root,mode,corner:target.dataset.resize||"",x:e.clientX,y:e.clientY,left:parseFloat(wrap.style.left)||0,top:parseFloat(wrap.style.top)||0,width:rect.width,ratio:img?.naturalWidth&&img?.naturalHeight?img.naturalWidth/img.naturalHeight:rect.width/Math.max(rect.height,1)};target.setPointerCapture?.(e.pointerId)};
 const moveImage=(e:React.PointerEvent<HTMLDivElement>)=>{const t=transformRef.current;if(!t)return;e.preventDefault();const dx=e.clientX-t.x,dy=e.clientY-t.y;if(t.mode==="move"){const left=t.left+dx,top=Math.max(0,t.top+dy);t.wrap.style.left=`${left}px`;t.wrap.style.top=`${top}px`;}else{const west=t.corner.includes("w"),north=t.corner.includes("n");const width=Math.max(70,t.width+(west?-dx:dx));let left=west?t.left+(t.width-width):t.left;let top=Math.max(0,north?t.top+(t.width-width)/t.ratio:t.top);t.wrap.style.width=`${width}px`;t.wrap.style.left=`${left}px`;t.wrap.style.top=`${top}px`;}};
 const endImage=(e?:React.PointerEvent<HTMLDivElement>)=>{const t=transformRef.current;if(!t){return}t.root.closest<HTMLElement>(".planner-box-libre")?.classList.remove("planner-box-dragging");t.wrap.style.filter="";t.wrap.style.opacity="";if(t.mode==="move"&&e){const prevPE=t.wrap.style.pointerEvents;t.wrap.style.pointerEvents="none";const dropEl=document.elementFromPoint(e.clientX,e.clientY) as HTMLElement|null;t.wrap.style.pointerEvents=prevPE;const dropFlex=dropEl?.closest<HTMLElement>("[data-flex-note-body]");if(dropFlex){const noteId=dropFlex.dataset.flexNoteBody;const img=t.wrap.querySelector("img") as HTMLImageElement|null;if(noteId&&img){const oldRect=t.wrap.getBoundingClientRect(),newRect=dropFlex.getBoundingClientRect();const left=Math.max(0,oldRect.left-newRect.left+dropFlex.scrollLeft),top=Math.max(0,oldRect.top-newRect.top+dropFlex.scrollTop);window.dispatchEvent(new CustomEvent("planner:flex-add-image",{detail:{noteId,src:img.src,left,top}}));t.wrap.remove();ensureRootHeight(t.root);save(t.box);transformRef.current=null;return}}const dropRoot=dropEl?.closest<HTMLElement>("[data-box-id]");const dropBox=dropRoot?.dataset.boxId as BoxId|undefined;if(dropRoot&&dropBox&&dropRoot!==t.root){const oldRect=t.wrap.getBoundingClientRect(),newRect=dropRoot.getBoundingClientRect();dropRoot.appendChild(t.wrap);t.wrap.style.left=`${Math.max(0,oldRect.left-newRect.left+dropRoot.scrollLeft)}px`;t.wrap.style.top=`${Math.max(0,oldRect.top-newRect.top+dropRoot.scrollTop)}px`;t.wrap.dataset.selected="true";ensureRootHeight(dropRoot);ensureRootHeight(t.root);save(t.box);save(dropBox);transformRef.current=null;return}}ensureRootHeight(t.root);save(t.box);transformRef.current=null};
 const cut=()=>{const e=refs.current[active];if(e){setCopied(e.innerHTML);e.innerHTML="";save(active)}}; const paste=()=>{const e=refs.current[active];if(e&&copied){e.insertAdjacentHTML("beforeend",copied);ensureRootHeight(e);save(active)}};
 const removeSelectedImage=()=>{const flexId=document.body.dataset.activeFlexNoteId;if(flexId){window.dispatchEvent(new CustomEvent("planner:flex-remove-selected"));return;}const root=refs.current[active];const sel=root?.querySelector<HTMLElement>('.planner-free-image[data-selected="true"]');if(!root||!sel)return;sel.remove();ensureRootHeight(root);save(active)};
 return <PageShell title="Notas" subtitle="Tocá una hoja y empezá. Las herramientas aparecen cuando las necesitás.">
  <style>{`.planner-free-image[data-selected="true"]{outline:2px solid #63a7d8;outline-offset:2px}.planner-free-image .resize-handle{display:none!important}.planner-free-image[data-selected="true"]{outline:2px solid #e8a28c!important;outline-offset:3px!important;border-radius:12px!important;z-index:30!important}.planner-free-image[data-selected="true"] .resize-handle[data-resize="se"]{display:block!important;width:20px!important;height:20px!important;right:-10px!important;bottom:-10px!important;top:auto!important;left:auto!important;background:#e8a28c!important;border:2px solid #fff!important;border-radius:999px!important;box-shadow:0 2px 6px rgba(0,0,0,.2)!important;z-index:40!important}.planner-free-image[data-selected="true"] .free-image-delete{display:flex!important;position:absolute!important;top:-14px!important;right:-14px!important;left:auto!important;transform:none!important;width:28px!important;height:28px!important;border-radius:999px!important;background:#fff!important;color:#dc2626!important;border:1px solid #d8dee8!important;align-items:center!important;justify-content:center!important;z-index:50!important;box-shadow:0 2px 8px rgba(0,0,0,.18)!important}.planner-free-image[data-selected="true"] .free-image-delete{display:flex}.planner-free-image[data-selected="true"] img{cursor:move}.resize-handle[data-resize="nw"],.resize-handle[data-resize="se"]{cursor:nwse-resize}.resize-handle[data-resize="ne"],.resize-handle[data-resize="sw"]{cursor:nesw-resize}.planner-box-libre{overflow:hidden!important;border-radius:16px!important}.planner-box-libre.planner-box-dragging{overflow:visible!important;position:relative;z-index:50}.planner-box-libre-body{overflow:visible!important;isolation:isolate}@media print{.planner-free-image{outline:none!important}.resize-handle,.free-image-delete{display:none!important}}`}</style>
  <div className="sticky top-0 z-30 -mx-4 mb-4 border-y border-border bg-background/95 px-4 py-2 backdrop-blur"><div className="flex flex-wrap items-center gap-1 sm:gap-1.5 [&_button]:min-h-9 [&_button]:px-2 sm:[&_button]:px-3 [&_select]:min-h-9">
  <select title="Fuente" aria-label="Fuente" value={font} onChange={e=>{setFont(e.target.value);cmd("fontName",e.target.value)}} className="h-11 w-[150px] rounded-xl border bg-card px-2 text-sm shadow-sm">{FONTS.map(f=><option key={f} value={f} style={{fontFamily:f}}>{f}</option>)}</select>
  <select title="Tamaño" aria-label="Tamaño" value={fontSize} onChange={e=>{setFontSize(e.target.value);cmd("fontSize",e.target.value)}} className="h-11 w-[70px] rounded-xl border bg-card px-2 text-sm shadow-sm">{SIZES.map(([label,v])=><option key={v} value={v}>{label}</option>)}</select>
  <IconTool title="Negrita" onClick={()=>cmd("bold")}><Bold/></IconTool><IconTool title="Cursiva" onClick={()=>cmd("italic")}><Italic/></IconTool><IconTool title="Subrayar" onClick={()=>cmd("underline")}><Underline/></IconTool>
  <IconTool title="Alinear a la izquierda" onClick={()=>cmd("justifyLeft")}><AlignLeft/></IconTool><IconTool title="Centrar" onClick={()=>cmd("justifyCenter")}><AlignCenter/></IconTool><IconTool title="Alinear a la derecha" onClick={()=>cmd("justifyRight")}><AlignRight/></IconTool><IconTool title="Justificar" onClick={()=>cmd("justifyFull")}><AlignJustify/></IconTool>
  <select title="Sombra de texto 0–5" aria-label="Sombra" value={shadow} onChange={e=>{setShadow(e.target.value);cmd("textShadow",e.target.value)}} className="h-11 w-[88px] rounded-xl border bg-card px-2 text-sm shadow-sm">{[0,1,2,3,4,5].map(n=><option key={n} value={String(n)}>Sombra {n}</option>)}</select><select title="Grosor del borde 0–5" aria-label="Borde" value={strokeWidth} onChange={e=>{setStrokeWidth(e.target.value);cmd("textStroke",e.target.value)}} className="h-11 w-[82px] rounded-xl border bg-card px-2 text-sm shadow-sm">{[0,1,2,3,4,5].map(n=><option key={n} value={String(n)}>Borde {n}</option>)}</select><button type="button" title="Color del borde" onMouseDown={e=>e.preventDefault()} onClick={()=>setPanel(panel==="stroke"?null:"stroke")} className="h-11 rounded-xl border bg-card px-3 text-sm shadow-sm">Borde 🎨</button><button type="button" title="Fondo de HOY o LIENZO LIBRE" onMouseDown={e=>e.preventDefault()} onClick={()=>setPanel(panel==="background"?null:"background")} className="h-11 rounded-xl border bg-card px-3 text-sm shadow-sm">🎨 Fondo</button>
  <IconTool title="Imagen" onClick={()=>fileRef.current?.click()}><ImagePlus/></IconTool><IconTool title="Stickers" onClick={()=>setPanel(panel==="stickers"?null:"stickers")}><SmilePlus/></IconTool><IconTool title="Color" onClick={()=>{if(document.body.dataset.activeFlexNoteId)window.dispatchEvent(new CustomEvent("planner:flex-save"));setPanel(panel==="colors"?null:"colors")}}><Palette/></IconTool><IconTool title="Resaltador" onClick={()=>{if(document.body.dataset.activeFlexNoteId)window.dispatchEvent(new CustomEvent("planner:flex-save"));setPanel(panel==="highlight"?null:"highlight")}}><Highlighter/></IconTool><IconTool title="Lápiz" onClick={()=>setPanel(panel==="ink"?null:"ink")}><Pencil/></IconTool><IconTool title="Más" onClick={()=>setPanel(panel==="more"?null:"more")}><MoreHorizontal/></IconTool>
  <button type="button" title="Restablecer formato" onMouseDown={e=>e.preventDefault()} onClick={()=>{cmd("removeFormat");setFont("Arial");setFontSize("3");setShadow("0");setStrokeWidth("0")}} className="h-11 rounded-xl border bg-card px-3 text-sm shadow-sm">Restablecer</button>
  <button type="button" title="Deshacer" onMouseDown={e=>e.preventDefault()} onClick={()=>inkTool!=="off"?undoInk():undoText()} className="grid h-11 w-11 place-items-center rounded-xl border bg-card text-xl shadow-sm">↶</button>
  <button type="button" title="Rehacer" onMouseDown={e=>e.preventDefault()} onClick={()=>inkTool!=="off"?redoInk():redoText()} className="grid h-11 w-11 place-items-center rounded-xl border bg-card text-xl shadow-sm">↷</button></div>
  {panel==="background"&&<div className="mt-2 rounded-2xl border bg-card p-3 shadow-lg">
   <div className="mb-2 flex items-center justify-between gap-2"><div className="text-xs font-semibold">Fondo de {BOXES.find(b=>b.id===active)?.title}</div><button type="button" className="rounded-full border px-2 py-1 text-xs" onClick={()=>{setPanel(null);setBackgroundExpanded(false)}}>Cerrar</button></div>
   <div className="flex flex-wrap items-center gap-2">
    {BOX_BACKGROUNDS.slice(0,8).map(c=><button key={c} type="button" className={`h-9 w-9 rounded-full border ${backgrounds[active].toUpperCase()===c.toUpperCase()?"ring-2 ring-primary ring-offset-1":"border-border"}`} style={{backgroundColor:c}} onClick={()=>{setBackgrounds(prev=>({...prev,[active]:c}));localStorage.setItem(`planner-box-background-${active}`,c)}}/>)}
    <button type="button" title="Ver más colores" className="grid h-9 w-9 place-items-center rounded-full border bg-card text-lg shadow-sm" onClick={()=>setBackgroundExpanded(v=>!v)}>…</button>
   </div>
   {backgroundExpanded&&<div className="mt-3 border-t border-border pt-3">
    <div className="mb-2 text-xs font-semibold">Más colores</div>
    <div className="grid grid-cols-6 gap-2">{CUSTOM_BACKGROUND_COLORS.map(c=><button key={c} type="button" className={`h-8 w-8 rounded-full border ${backgrounds[active].toUpperCase()===c.toUpperCase()?"ring-2 ring-primary ring-offset-1":"border-border"}`} style={{backgroundColor:c}} onClick={()=>{setBackgrounds(prev=>({...prev,[active]:c}));localStorage.setItem(`planner-box-background-${active}`,c)}}/>)}</div>
   </div>}
   <div className="mt-3 flex flex-wrap items-center gap-2 border-t border-border pt-3">
    <button type="button" className="inline-flex items-center gap-2 rounded-full border px-3 py-2 text-xs" onClick={()=>{const c="#FFFFFF";setBackgrounds(prev=>({...prev,[active]:c}));localStorage.setItem(`planner-box-background-${active}`,c)}}><span className="h-5 w-5 rounded-full border bg-white"/>Sin fondo</button>
    <label className="inline-flex cursor-pointer items-center gap-2 rounded-full border px-3 py-2 text-xs"><Palette className="h-4 w-4"/>Más colores…<span className="relative h-6 w-6 shrink-0 overflow-hidden rounded-full border border-border shadow-sm" style={{backgroundColor:backgrounds[active]}}><input type="color" value={backgrounds[active]} onChange={e=>{const c=e.target.value;setBackgrounds(prev=>({...prev,[active]:c}));localStorage.setItem(`planner-box-background-${active}`,c)}} className="absolute inset-[-10px] h-14 w-14 cursor-pointer opacity-0" aria-label="Elegir cualquier color de fondo"/></span></label>
   </div>
  </div>}
  {panel==="stroke"&&<div className="mt-2 flex flex-wrap items-center gap-2 rounded-xl border bg-card p-2"><span className="mr-1 text-xs font-semibold">Color del borde</span>{COLORS.map(c=><button key={c} type="button" className="h-8 w-8 rounded-full border" style={{backgroundColor:c}} onClick={()=>cmd("strokeColor",c)}/>)}<label className="flex cursor-pointer items-center gap-2 rounded-full border px-3 py-1 text-sm">Más colores <span className="relative h-7 w-7 shrink-0 overflow-hidden rounded-full border border-border shadow-sm" style={{backgroundColor:strokeColor}}><input type="color" value={strokeColor} onChange={e=>cmd("strokeColor",e.target.value)} className="absolute inset-[-8px] h-12 w-12 cursor-pointer opacity-0"/></span></label></div>}
  {panel==="colors"&&<div className="mt-2 flex flex-wrap items-center gap-2 rounded-xl border bg-card p-2">{COLORS.map(c=><button key={c} className="h-8 w-8 rounded-full border" style={{backgroundColor:c}} onClick={()=>cmd("foreColor",c)}/>)}<label className="flex h-8 w-8 cursor-pointer items-center justify-center rounded-full border" title="Elegir cualquier color" style={{background:"conic-gradient(red,yellow,lime,cyan,blue,magenta,red)"}}><input type="color" className="h-0 w-0 opacity-0" onChange={e=>cmd("foreColor",e.target.value)}/></label></div>}
  {panel==="highlight"&&<div className="mt-2 flex flex-wrap items-center gap-2 rounded-xl border bg-card p-2"><button type="button" className="rounded-full border px-3 py-1.5 text-sm font-medium" onMouseDown={e=>e.preventDefault()} onClick={()=>cmd("hiliteColor","transparent")}>🚫 Sin resaltado</button>{HILITES.filter(c=>c!=="#FFFFFF").map(c=><button key={c} type="button" className="h-8 w-8 rounded-full border" style={{backgroundColor:c}} onMouseDown={e=>e.preventDefault()} onClick={()=>cmd("hiliteColor",c)}/>)}<label className="flex h-8 w-8 cursor-pointer items-center justify-center rounded-full border" title="Elegir cualquier color" style={{background:"conic-gradient(red,yellow,lime,cyan,blue,magenta,red)"}}><input type="color" className="h-0 w-0 opacity-0" onChange={e=>cmd("hiliteColor",e.target.value)}/></label></div>}
  {panel==="ink"&&<div className="mt-2 rounded-xl border bg-card p-1.5 shadow-sm">
   <div className="flex max-w-full items-center gap-1.5 overflow-x-auto whitespace-nowrap pb-0.5 [-webkit-overflow-scrolling:touch]">
    <button type="button" title="Lápiz" aria-label="Lápiz" className={`inline-flex h-10 min-w-10 shrink-0 items-center justify-center rounded-full border px-2 ${inkTool==="pen"?"bg-accent":""}`} onClick={()=>setInkTool("pen")}><Pencil className="h-4 w-4"/><span className="ml-1 hidden sm:inline">Lápiz</span></button>
    <button type="button" title="Goma" aria-label="Goma" className={`inline-flex h-10 min-w-10 shrink-0 items-center justify-center rounded-full border px-2 ${inkTool==="eraser"?"bg-accent":""}`} onClick={()=>setInkTool("eraser")}><Eraser className="h-4 w-4"/><span className="ml-1 hidden sm:inline">Goma</span></button>
    <button type="button" title="Deshacer trazo" aria-label="Deshacer trazo" className="h-10 min-w-10 shrink-0 rounded-full border px-2" onClick={()=>undoInk()}>↶</button>
    <button type="button" title="Rehacer trazo" aria-label="Rehacer trazo" className="h-10 min-w-10 shrink-0 rounded-full border px-2" onClick={()=>redoInk()}>↷</button>
    <label title="Color del lápiz" className="relative inline-flex h-10 min-w-10 shrink-0 cursor-pointer items-center justify-center rounded-full border px-2"><span className="h-5 w-5 rounded-full border" style={{backgroundColor:inkColor}}/><input aria-label="Color del lápiz" type="color" value={inkColor} onChange={e=>setInkColor(e.target.value)} className="absolute inset-0 h-full w-full cursor-pointer opacity-0"/></label>
    <button type="button" title="Más opciones del lápiz" aria-label="Más opciones del lápiz" className={`h-10 min-w-10 shrink-0 rounded-full border px-2 ${inkMore?"bg-accent":""}`} onClick={()=>setInkMore(v=>!v)}>•••</button>
    <button type="button" className="h-10 shrink-0 rounded-full border px-3 text-sm font-semibold" onClick={()=>{setInkTool("off");setInkMore(false);setPanel(null)}}>✓ <span className="hidden sm:inline">Terminar</span></button>
   </div>
   {inkMore&&<div className="mt-1.5 flex flex-wrap items-center gap-2 border-t pt-1.5">
    <label className="inline-flex h-10 items-center gap-2 rounded-full border px-3 text-xs">Grosor <input aria-label="Grosor del lápiz" type="range" min="2" max="12" value={inkWidth} onChange={e=>setInkWidth(Number(e.target.value))} className="w-20"/><b>{inkWidth}</b></label>
    <button type="button" disabled={inkRecognizing} className="h-10 rounded-full border bg-accent px-3 text-sm font-semibold disabled:opacity-60" onClick={convertInkToText}>{inkRecognizing?"Convirtiendo…":"Convertir a texto"}</button>
   </div>}
  </div>}
  {panel==="more"&&<div className="mt-2 flex flex-wrap gap-2 rounded-xl border bg-card p-2"><button className="rounded-lg border px-3 py-2" onClick={cut}><Scissors className="inline h-4 w-4"/> Cortar caja</button><button className="rounded-lg border px-3 py-2" onClick={()=>setCopied(refs.current[active]?.innerHTML??"")}><Copy className="inline h-4 w-4"/> Copiar</button><button className="rounded-lg border px-3 py-2" onClick={paste}>Pegar</button><button className="rounded-lg border px-3 py-2 text-destructive" onClick={removeSelectedImage}><Trash2 className="inline h-4 w-4"/> Quitar imagen seleccionada</button><button className="rounded-lg border px-3 py-2 text-destructive" onClick={()=>{const e=refs.current[active];if(e){e.innerHTML="";save(active)}}}><Trash2 className="inline h-4 w-4"/> Vaciar</button></div>}
  <div className="mt-1 text-xs text-muted-foreground">Editando: <b>{BOXES.find(b=>b.id===active)?.title}</b></div></div>
  <input ref={fileRef} type="file" accept="image/*" className="hidden" onChange={e=>{addImage(e.target.files?.[0]);e.currentTarget.value=""}}/>
  <div className="space-y-4">{BOXES.map(box=><section key={box.id} onPointerDown={()=>selectBase(box.id)} style={{backgroundColor:backgrounds[box.id]}} className={`planner-box-libre rounded-[1.4rem] border shadow-sm ${active===box.id?"border-[#D9A596]/60":"border-border"}`}><div className={`${box.tone} border-b border-border px-4 py-2 text-xs font-extrabold tracking-wide`}>{box.title}</div><div className="relative min-h-[420px]"><div ref={el=>{refs.current[box.id]=el;if(el){upgradeImages(el);ensureRootHeight(el);setTimeout(()=>sizeInkCanvas(box.id,inkCanvasRefs.current[box.id]),0)}}} data-box-id={box.id} contentEditable={inkTool==="off"} suppressContentEditableWarning onFocus={()=>selectBase(box.id)} onBeforeInput={()=>pushTextUndo(box.id)} onInput={()=>{remember(box.id);save(box.id);setTimeout(()=>sizeInkCanvas(box.id,inkCanvasRefs.current[box.id]),0)}} onKeyUp={()=>remember(box.id)} onMouseUp={()=>remember(box.id)} onTouchEnd={()=>setTimeout(()=>remember(box.id),0)} onPointerDown={e=>{if(inkTool==="off")startImageTransform(box.id,e)}} onPointerMove={e=>{if(inkTool==="off")moveImage(e)}} onPointerUp={e=>{if(inkTool==="off")endImage(e)}} onPointerCancel={e=>{if(inkTool==="off")endImage(e)}} className="planner-box-libre-body relative z-10 min-h-[420px] px-4 py-4 text-base leading-7 outline-none empty:before:text-muted-foreground empty:before:content-[attr(data-placeholder)]" data-placeholder={box.placeholder}/><canvas ref={c=>sizeInkCanvas(box.id,c)} className="absolute left-0 top-0 z-20 touch-none" style={{pointerEvents:inkTool==="off"?"none":"auto",cursor:inkTool==="eraser"?"cell":"crosshair"}} onPointerDown={e=>startInk(box.id,e)} onPointerMove={e=>moveInk(box.id,e)} onPointerUp={()=>endInk(box.id)} onPointerCancel={()=>endInk(box.id)}/></div></section>)}</div>
  <div style={{marginTop:"20px"}}><FlexibleNotes /></div>
 </PageShell>
}
function IconTool({children,title,onClick}:{children:React.ReactNode;title:string;onClick:()=>void}){return <button type="button" title={title} onMouseDown={e=>e.preventDefault()} onClick={onClick} className="grid h-11 w-11 place-items-center rounded-xl border bg-card shadow-sm [&_svg]:h-5 [&_svg]:w-5">{children}</button>}
