import { useEffect, useRef, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { AlignCenter, AlignJustify, AlignLeft, AlignRight, Bold, Copy, Highlighter, ImagePlus, Italic, MoreHorizontal, Palette, Scissors, SmilePlus, Trash2, Underline } from "lucide-react";
import { AppGate } from "@/components/planner/AppGate";
import { PageShell } from "@/components/planner/PageShell";
import { FlexibleNotes } from "@/components/planner/FlexibleNotes";

export const Route = createFileRoute("/notas")({ component: () => <AppGate><NotasPage /></AppGate> });
type BoxId="hoy"|"libre"; type Panel="stickers"|"colors"|"highlight"|"background"|"stroke"|"more"|null; type StickerGroup="Favoritos"|"Agenda"|"Deco"|"Comida"|"Viajes"|"Caritas";
const BOXES=[{id:"hoy" as BoxId,title:"HOY",tone:"bg-[#F7E5DF]",placeholder:"Tocá acá y escribí..."},{id:"libre" as BoxId,title:"LIENZO LIBRE",tone:"bg-[#F3E8E5]",placeholder:"Texto, imágenes, stickers..."}];
const STICKERS:Record<StickerGroup,string[]>={Favoritos:["⭐","❤️","✨","🌸","🦋","🌈","☀️","📌","💡","✅","🎯","📝"],Agenda:["📅","⏰","⏳","📌","📎","✏️","🖊️","📝","📚","💻","📞","💬","✅","❗","💡","🎯","💰","🛒"],Deco:["🎀","🌸","🌷","🌼","🌻","🌹","🍀","🌿","🍃","🦋","🐝","🌙","⭐","✨","💫","☁️","🌈","🕯️"],Comida:["☕","🫖","🍰","🎂","🍓","🍒","🍋","🍉","🥐","🍞","🥗","🍕","🍝","🍫","🍪","🥤","🍷","🧁"],Viajes:["✈️","🚗","🚲","🧳","🗺️","📍","🏖️","🏕️","🏨","🌊","⛰️","🌴","🎒","📷","🚆","🛳️","🌎","🧭"],Caritas:["😊","🥰","😍","🤩","😌","😂","😉","😎","🤗","🥳","😴","🤔","🙌","👏","💪","🙏","💖","💕"]};
const SIZES:[string,string][]=[["10","1"],["13","2"],["16","3"],["18","4"],["24","5"],["32","6"],["48","7"]];
const BOX_BACKGROUNDS=["#FFFFFF","#FCE8EC","#FDEAD7","#FFF4CC","#EAF4E4","#DFF3E8","#E4F1F5","#E6ECFA","#EEE8F6","#F4E4F7","#F4E8DE","#F1EFEA"];
const COLORS=["#111111","#A84F4F","#D26A4C","#C48A2F","#66508D","#4F6E98","#B34F83","#4E7C72","#2F6F5F","#31708E"]; const HILITES=["#FFF3A3","#FFD9A0","#FFB3C1","#C9F2C7","#B8E3FF","#E3D1FF","#FFFFFF"]; const FONTS=["Arial","Verdana","Tahoma","Trebuchet MS","Georgia","Times New Roman","Courier New","Comic Sans MS","Segoe UI","Calibri","Garamond","Helvetica","Palatino","Century Gothic","Lucida Sans","Lucida Console","Book Antiqua","Impact","Consolas","Franklin Gothic Medium","Rockwell","Baskerville","Cambria","Candara"]; const storageKey=(id:BoxId)=>`planner-lienzo-${id}-v2`;
const handle=(corner:string)=>`<span class="resize-handle" data-resize="${corner}" style="position:absolute;width:14px;height:14px;border:2px solid #fff;background:#63a7d8;border-radius:50%;z-index:4;${corner.includes("n")?"top:-8px;":"bottom:-8px;"}${corner.includes("w")?"left:-8px;":"right:-8px;"}"></span>`;
const deleteHandle=`<span class="free-image-delete" contenteditable="false" data-action="delete" style="position:absolute;top:-34px;left:50%;transform:translateX(-50%);width:30px;height:30px;border-radius:50%;background:#c0392b;color:#fff;display:none;align-items:center;justify-content:center;font-size:17px;font-weight:800;line-height:1;z-index:7;cursor:pointer;box-shadow:0 2px 5px rgba(0,0,0,.35);">×</span>`;
const freeImageHtml=(src:string)=>`<span class="planner-free-image" contenteditable="false" data-selected="true" style="position:absolute;left:16px;top:16px;width:45%;max-width:calc(100% - 32px);display:block;z-index:2;touch-action:none;user-select:none;"><img src="${src}" alt="Imagen" draggable="false" style="display:block;width:100%;height:auto;border-radius:10px;pointer-events:auto;"/>${deleteHandle}${handle("nw")}${handle("ne")}${handle("sw")}${handle("se")}</span>`;
function upgradeImages(root:HTMLElement){root.querySelectorAll<HTMLElement>(".planner-free-image").forEach(w=>{if(!w.querySelector(".free-image-delete"))w.insertAdjacentHTML("afterbegin",deleteHandle)});root.querySelectorAll<HTMLImageElement>("img").forEach(img=>{if(img.closest(".planner-free-image"))return;const wrap=document.createElement("span");wrap.innerHTML=freeImageHtml(img.src);img.replaceWith(wrap.firstElementChild!);});}
function ensureRootHeight(root:HTMLElement){let bottom=192;root.querySelectorAll<HTMLElement>(".planner-free-image").forEach(w=>{const top=parseFloat(w.style.top)||0;const width=w.getBoundingClientRect().width||parseFloat(w.style.width)||120;const img=w.querySelector("img") as HTMLImageElement|null;const ratio=img?.naturalWidth&&img?.naturalHeight?img.naturalWidth/img.naturalHeight:1;bottom=Math.max(bottom,top+width/Math.max(ratio,.1)+28)});root.style.minHeight=`${Math.ceil(bottom)}px`;}
function deselectAllImages(except?:HTMLElement){document.querySelectorAll<HTMLElement>(".planner-free-image, .planner-flex-free-image").forEach(w=>{if(w!==except)w.dataset.selected="false"})}
function applyInlineStyle(range:Range,styles:Record<string,string>){if(range.collapsed)return;const span=document.createElement("span");Object.assign(span.style,styles);try{const fragment=range.extractContents();span.appendChild(fragment);range.insertNode(span);const next=document.createRange();next.selectNodeContents(span);const sel=window.getSelection();sel?.removeAllRanges();sel?.addRange(next)}catch{/* keep editor usable if browser rejects a complex range */}}

function NotasPage(){
 const refs=useRef<Record<BoxId,HTMLDivElement|null>>({hoy:null,libre:null}); const fileRef=useRef<HTMLInputElement>(null); const selectionRef=useRef<Range|null>(null); const transformRef=useRef<{box:BoxId;wrap:HTMLElement;root:HTMLElement;mode:"move"|"resize";corner:string;x:number;y:number;left:number;top:number;width:number;ratio:number}|null>(null); const [active,setActive]=useState<BoxId>("hoy"); const [panel,setPanel]=useState<Panel>(null); const [group,setGroup]=useState<StickerGroup>("Favoritos"); const [copied,setCopied]=useState(""); const [font,setFont]=useState("Arial"); const [fontSize,setFontSize]=useState("3"); const [shadow,setShadow]=useState("0"); const [strokeWidth,setStrokeWidth]=useState("0"); const [strokeColor,setStrokeColor]=useState("#111111"); const [backgrounds,setBackgrounds]=useState<Record<BoxId,string>>({hoy:"#FFFFFF",libre:"#FFFFFF"});
 useEffect(()=>{const next={hoy:localStorage.getItem("planner-box-background-hoy")||"#FFFFFF",libre:localStorage.getItem("planner-box-background-libre")||"#FFFFFF"};setBackgrounds(next);BOXES.forEach(({id})=>{const el=refs.current[id];if(el){el.innerHTML=localStorage.getItem(storageKey(id))??"";upgradeImages(el);ensureRootHeight(el);localStorage.setItem(storageKey(id),el.innerHTML)}})},[]);
 useEffect(()=>{const onTouchStart=(e:TouchEvent)=>{const t=e.target as HTMLElement;if(t.closest(".planner-free-image, .planner-flex-free-image"))e.preventDefault()};document.addEventListener("touchstart",onTouchStart,{passive:false});return()=>document.removeEventListener("touchstart",onTouchStart)},[]);
 useEffect(()=>{const onSelectionChange=()=>{const sel=window.getSelection();if(!sel||!sel.rangeCount||sel.isCollapsed)return;const r=sel.getRangeAt(0);for(const id of ["hoy","libre"] as BoxId[]){const root=refs.current[id];if(root&&root.contains(r.startContainer)&&root.contains(r.endContainer)){delete document.body.dataset.activeFlexNoteId;setActive(id);selectionRef.current=r.cloneRange();break}}};document.addEventListener("selectionchange",onSelectionChange);return()=>document.removeEventListener("selectionchange",onSelectionChange)},[]);
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(e.key!=="Delete"&&e.key!=="Backspace")return;const sel=document.querySelector<HTMLElement>('.planner-free-image[data-selected="true"],.planner-flex-free-image[data-selected="true"]');if(!sel)return;e.preventDefault();if(sel.classList.contains("planner-flex-free-image")){window.dispatchEvent(new CustomEvent("planner:flex-remove-selected"));return}const root=sel.closest<HTMLElement>("[contenteditable]");sel.remove();if(root){ensureRootHeight(root);const box=(Object.keys(refs.current) as BoxId[]).find(k=>refs.current[k]===root);if(box)save(box)}};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[]);
 useEffect(()=>{const onBaseAdd=(ev:Event)=>{const e=ev as CustomEvent<{box:BoxId;src:string;left?:number;top?:number}>;const{box,src,left,top}=e.detail||({} as {box?:BoxId;src?:string;left?:number;top?:number});if(!box||!src)return;const root=refs.current[box];if(!root)return;root.insertAdjacentHTML("beforeend",freeImageHtml(src));if(left!==undefined||top!==undefined){const inserted=root.lastElementChild as HTMLElement|null;if(inserted){if(left!==undefined)inserted.style.left=`${Math.max(0,left)}px`;if(top!==undefined)inserted.style.top=`${Math.max(0,top)}px`}}upgradeImages(root);ensureRootHeight(root);save(box)};window.addEventListener("planner:base-add-image",onBaseAdd as EventListener);return()=>window.removeEventListener("planner:base-add-image",onBaseAdd as EventListener)},[]);
 const save=(id:BoxId)=>{const el=refs.current[id];if(el)localStorage.setItem(storageKey(id),el.innerHTML)}; const remember=(id:BoxId=active)=>{const s=window.getSelection(),root=refs.current[id];if(s&&s.rangeCount&&root?.contains(s.getRangeAt(0).startContainer)&&root.contains(s.getRangeAt(0).endContainer))selectionRef.current=s.getRangeAt(0).cloneRange()}; const focus=()=>{refs.current[active]?.focus({preventScroll:true});const r=selectionRef.current,s=window.getSelection();if(r&&s){s.removeAllRanges();s.addRange(r)}}; const cmd=(c:string,v?:string)=>{const flexId=document.body.dataset.activeFlexNoteId;if(flexId){window.dispatchEvent(new CustomEvent("planner:flex-format",{detail:{command:c,value:v}}));return;}focus();const r=selectionRef.current;if(c==="textShadow"&&r){const n=Number(v||0);applyInlineStyle(r,{textShadow:n?`0 ${n}px ${Math.max(1,n*2)}px rgba(0,0,0,.45)`:"none"})}else if(c==="textStroke"&&r){const n=Number(v||0);applyInlineStyle(r,{WebkitTextStroke:n?`${n}px ${strokeColor}`:"0 transparent",paintOrder:"stroke fill"})}else if(c==="strokeColor"&&r){setStrokeColor(v||"#111111");applyInlineStyle(r,{WebkitTextStroke:Number(strokeWidth)?`${strokeWidth}px ${v||"#111111"}`:"0 transparent",paintOrder:"stroke fill"})}else document.execCommand(c,false,v);remember(active);save(active)};
 const selectBase=(id:BoxId)=>{delete document.body.dataset.activeFlexNoteId;setActive(id)};
 const addImage=(file?:File)=>{if(!file)return;const r=new FileReader();r.onload=()=>{const src=String(r.result);const flexId=document.body.dataset.activeFlexNoteId;if(flexId){window.dispatchEvent(new CustomEvent("planner:flex-add-image",{detail:{noteId:flexId,src}}));return;}const root=refs.current[active];if(!root)return;deselectAllImages();root.insertAdjacentHTML("beforeend",freeImageHtml(src));ensureRootHeight(root);save(active)};r.readAsDataURL(file)};
 const startImageTransform=(box:BoxId,e:React.PointerEvent<HTMLDivElement>)=>{const target=e.target as HTMLElement;const wrap=target.closest<HTMLElement>(".planner-free-image");const root=refs.current[box];if(!wrap||!root){deselectAllImages();return;}selectBase(box);const prev=transformRef.current;if(prev){prev.root.closest<HTMLElement>(".planner-box-libre")?.classList.remove("planner-box-dragging");prev.wrap.style.zIndex="";prev.wrap.style.filter="";prev.wrap.style.opacity="";ensureRootHeight(prev.root);save(prev.box);transformRef.current=null}e.preventDefault();e.stopPropagation();if(target.dataset.action==="delete"){wrap.remove();ensureRootHeight(root);save(box);return;}deselectAllImages(wrap);wrap.dataset.selected="true";const rect=wrap.getBoundingClientRect(),img=wrap.querySelector("img") as HTMLImageElement|null;const mode=target.dataset.resize?"resize":"move";if(mode==="move"){root.closest<HTMLElement>(".planner-box-libre")?.classList.add("planner-box-dragging");wrap.style.zIndex="25";wrap.style.filter="drop-shadow(0 8px 16px rgba(0,0,0,.35))";wrap.style.opacity="0.92"}transformRef.current={box,wrap,root,mode,corner:target.dataset.resize||"",x:e.clientX,y:e.clientY,left:parseFloat(wrap.style.left)||0,top:parseFloat(wrap.style.top)||0,width:rect.width,ratio:img?.naturalWidth&&img?.naturalHeight?img.naturalWidth/img.naturalHeight:rect.width/Math.max(rect.height,1)};target.setPointerCapture?.(e.pointerId)};
 const moveImage=(e:React.PointerEvent<HTMLDivElement>)=>{const t=transformRef.current;if(!t)return;e.preventDefault();const dx=e.clientX-t.x,dy=e.clientY-t.y;if(t.mode==="move"){const left=t.left+dx,top=Math.max(0,t.top+dy);t.wrap.style.left=`${left}px`;t.wrap.style.top=`${top}px`;}else{const west=t.corner.includes("w"),north=t.corner.includes("n");const width=Math.max(70,t.width+(west?-dx:dx));let left=west?t.left+(t.width-width):t.left;let top=Math.max(0,north?t.top+(t.width-width)/t.ratio:t.top);t.wrap.style.width=`${width}px`;t.wrap.style.left=`${left}px`;t.wrap.style.top=`${top}px`;}};
 const endImage=(e?:React.PointerEvent<HTMLDivElement>)=>{const t=transformRef.current;if(!t){return}t.root.closest<HTMLElement>(".planner-box-libre")?.classList.remove("planner-box-dragging");t.wrap.style.filter="";t.wrap.style.opacity="";if(t.mode==="move"&&e){const prevPE=t.wrap.style.pointerEvents;t.wrap.style.pointerEvents="none";const dropEl=document.elementFromPoint(e.clientX,e.clientY) as HTMLElement|null;t.wrap.style.pointerEvents=prevPE;const dropFlex=dropEl?.closest<HTMLElement>("[data-flex-note-body]");if(dropFlex){const noteId=dropFlex.dataset.flexNoteBody;const img=t.wrap.querySelector("img") as HTMLImageElement|null;if(noteId&&img){const oldRect=t.wrap.getBoundingClientRect(),newRect=dropFlex.getBoundingClientRect();const left=Math.max(0,oldRect.left-newRect.left+dropFlex.scrollLeft),top=Math.max(0,oldRect.top-newRect.top+dropFlex.scrollTop);window.dispatchEvent(new CustomEvent("planner:flex-add-image",{detail:{noteId,src:img.src,left,top}}));t.wrap.remove();ensureRootHeight(t.root);save(t.box);transformRef.current=null;return}}const dropRoot=dropEl?.closest<HTMLElement>("[data-box-id]");const dropBox=dropRoot?.dataset.boxId as BoxId|undefined;if(dropRoot&&dropBox&&dropRoot!==t.root){const oldRect=t.wrap.getBoundingClientRect(),newRect=dropRoot.getBoundingClientRect();dropRoot.appendChild(t.wrap);t.wrap.style.left=`${Math.max(0,oldRect.left-newRect.left+dropRoot.scrollLeft)}px`;t.wrap.style.top=`${Math.max(0,oldRect.top-newRect.top+dropRoot.scrollTop)}px`;t.wrap.dataset.selected="true";ensureRootHeight(dropRoot);ensureRootHeight(t.root);save(t.box);save(dropBox);transformRef.current=null;return}}ensureRootHeight(t.root);save(t.box);transformRef.current=null};
 const cut=()=>{const e=refs.current[active];if(e){setCopied(e.innerHTML);e.innerHTML="";save(active)}}; const paste=()=>{const e=refs.current[active];if(e&&copied){e.insertAdjacentHTML("beforeend",copied);ensureRootHeight(e);save(active)}};
 const removeSelectedImage=()=>{const flexId=document.body.dataset.activeFlexNoteId;if(flexId){window.dispatchEvent(new CustomEvent("planner:flex-remove-selected"));return;}const root=refs.current[active];const sel=root?.querySelector<HTMLElement>('.planner-free-image[data-selected="true"]');if(!root||!sel)return;sel.remove();ensureRootHeight(root);save(active)};
 return <PageShell title="Notas" subtitle="Tocá una hoja y empezá. Las herramientas aparecen cuando las necesitás.">
  <style>{`.planner-free-image[data-selected="true"]{outline:2px solid #63a7d8;outline-offset:2px}.planner-free-image .resize-handle{display:none}.planner-free-image[data-selected="true"] .resize-handle{display:block}.planner-free-image[data-selected="true"] .free-image-delete{display:flex}.planner-free-image[data-selected="true"] img{cursor:move}.resize-handle[data-resize="nw"],.resize-handle[data-resize="se"]{cursor:nwse-resize}.resize-handle[data-resize="ne"],.resize-handle[data-resize="sw"]{cursor:nesw-resize}.planner-box-libre{overflow:hidden!important;border-radius:16px!important}.planner-box-libre.planner-box-dragging{overflow:visible!important;position:relative;z-index:50}.planner-box-libre-body{overflow:visible!important;isolation:isolate}@media print{.planner-free-image{outline:none!important}.resize-handle,.free-image-delete{display:none!important}}`}</style>
  <div className="sticky top-0 z-30 -mx-4 mb-4 border-y border-border bg-background/95 px-4 py-2 backdrop-blur"><div className="flex flex-wrap items-center gap-1.5">
  <select title="Fuente" aria-label="Fuente" value={font} onChange={e=>{setFont(e.target.value);cmd("fontName",e.target.value)}} className="h-11 w-[150px] rounded-xl border bg-card px-2 text-sm shadow-sm">{FONTS.map(f=><option key={f} value={f} style={{fontFamily:f}}>{f}</option>)}</select>
  <select title="Tamaño" aria-label="Tamaño" value={fontSize} onChange={e=>{setFontSize(e.target.value);cmd("fontSize",e.target.value)}} className="h-11 w-[70px] rounded-xl border bg-card px-2 text-sm shadow-sm">{SIZES.map(([label,v])=><option key={v} value={v}>{label}</option>)}</select>
  <IconTool title="Negrita" onClick={()=>cmd("bold")}><Bold/></IconTool><IconTool title="Cursiva" onClick={()=>cmd("italic")}><Italic/></IconTool><IconTool title="Subrayar" onClick={()=>cmd("underline")}><Underline/></IconTool>
  <IconTool title="Alinear a la izquierda" onClick={()=>cmd("justifyLeft")}><AlignLeft/></IconTool><IconTool title="Centrar" onClick={()=>cmd("justifyCenter")}><AlignCenter/></IconTool><IconTool title="Alinear a la derecha" onClick={()=>cmd("justifyRight")}><AlignRight/></IconTool><IconTool title="Justificar" onClick={()=>cmd("justifyFull")}><AlignJustify/></IconTool>
  <select title="Sombra de texto 0–5" aria-label="Sombra" value={shadow} onChange={e=>{setShadow(e.target.value);cmd("textShadow",e.target.value)}} className="h-11 w-[88px] rounded-xl border bg-card px-2 text-sm shadow-sm">{[0,1,2,3,4,5].map(n=><option key={n} value={String(n)}>Sombra {n}</option>)}</select><select title="Grosor del borde 0–5" aria-label="Borde" value={strokeWidth} onChange={e=>{setStrokeWidth(e.target.value);cmd("textStroke",e.target.value)}} className="h-11 w-[82px] rounded-xl border bg-card px-2 text-sm shadow-sm">{[0,1,2,3,4,5].map(n=><option key={n} value={String(n)}>Borde {n}</option>)}</select><button type="button" title="Color del borde" onMouseDown={e=>e.preventDefault()} onClick={()=>setPanel(panel==="stroke"?null:"stroke")} className="h-11 rounded-xl border bg-card px-3 text-sm shadow-sm">Borde 🎨</button><button type="button" title="Fondo de HOY o LIENZO LIBRE" onMouseDown={e=>e.preventDefault()} onClick={()=>setPanel(panel==="background"?null:"background")} className="h-11 rounded-xl border bg-card px-3 text-sm shadow-sm">🎨 Fondo</button>
  <IconTool title="Imagen" onClick={()=>fileRef.current?.click()}><ImagePlus/></IconTool><IconTool title="Stickers" onClick={()=>setPanel(panel==="stickers"?null:"stickers")}><SmilePlus/></IconTool><IconTool title="Color" onClick={()=>{if(document.body.dataset.activeFlexNoteId)window.dispatchEvent(new CustomEvent("planner:flex-save"));setPanel(panel==="colors"?null:"colors")}}><Palette/></IconTool><IconTool title="Resaltador" onClick={()=>{if(document.body.dataset.activeFlexNoteId)window.dispatchEvent(new CustomEvent("planner:flex-save"));setPanel(panel==="highlight"?null:"highlight")}}><Highlighter/></IconTool><IconTool title="Más" onClick={()=>setPanel(panel==="more"?null:"more")}><MoreHorizontal/></IconTool></div>
  {panel==="background"&&<div className="mt-2 rounded-2xl border bg-card p-3 shadow-lg"><div className="mb-2 text-xs font-semibold">Colores pastel · Fondo de {BOXES.find(b=>b.id===active)?.title}</div><div className="flex flex-wrap gap-2">{BOX_BACKGROUNDS.map(c=><button key={c} type="button" title={c} aria-label={`Elegir fondo ${c}`} className={`h-9 w-9 rounded-full border ${backgrounds[active].toUpperCase()===c.toUpperCase()?"ring-2 ring-primary ring-offset-1":"border-border"}`} style={{backgroundColor:c}} onClick={()=>{setBackgrounds(prev=>({...prev,[active]:c}));localStorage.setItem(`planner-box-background-${active}`,c);setPanel(null)}}/>)}</div><div className="mt-3 border-t border-border pt-3"><label className="inline-flex cursor-pointer items-center gap-2 rounded-full border bg-card px-3 py-2 text-sm shadow-sm"><Palette className="h-4 w-4"/> Más colores… <span className="relative h-7 w-7 shrink-0 overflow-hidden rounded-full border border-border shadow-sm" style={{backgroundColor:backgrounds[active]}}><input type="color" value={backgrounds[active]} onChange={e=>{const c=e.target.value;setBackgrounds(prev=>({...prev,[active]:c}));localStorage.setItem(`planner-box-background-${active}`,c)}} className="absolute inset-[-8px] h-12 w-12 cursor-pointer opacity-0" aria-label="Elegir cualquier color de fondo"/></span></label></div></div>}
  {panel==="stroke"&&<div className="mt-2 flex flex-wrap items-center gap-2 rounded-xl border bg-card p-2"><span className="mr-1 text-xs font-semibold">Color del borde</span>{COLORS.map(c=><button key={c} type="button" className="h-8 w-8 rounded-full border" style={{backgroundColor:c}} onClick={()=>cmd("strokeColor",c)}/>)}<label className="flex cursor-pointer items-center gap-2 rounded-lg border px-3 py-1 text-sm">Más colores <input type="color" value={strokeColor} onChange={e=>cmd("strokeColor",e.target.value)}/></label></div>}
  {panel==="colors"&&<div className="mt-2 flex flex-wrap items-center gap-2 rounded-xl border bg-card p-2">{COLORS.map(c=><button key={c} className="h-8 w-8 rounded-full border" style={{backgroundColor:c}} onClick={()=>cmd("foreColor",c)}/>)}<label className="flex h-8 w-8 cursor-pointer items-center justify-center rounded-full border" title="Elegir cualquier color" style={{background:"conic-gradient(red,yellow,lime,cyan,blue,magenta,red)"}}><input type="color" className="h-0 w-0 opacity-0" onChange={e=>cmd("foreColor",e.target.value)}/></label></div>}
  {panel==="highlight"&&<div className="mt-2 flex flex-wrap items-center gap-2 rounded-xl border bg-card p-2">{HILITES.map(c=><button key={c} className="h-8 w-8 rounded-full border" style={{backgroundColor:c}} onClick={()=>cmd("hiliteColor",c)}/>)}<label className="flex h-8 w-8 cursor-pointer items-center justify-center rounded-full border" title="Elegir cualquier color" style={{background:"conic-gradient(red,yellow,lime,cyan,blue,magenta,red)"}}><input type="color" className="h-0 w-0 opacity-0" onChange={e=>cmd("hiliteColor",e.target.value)}/></label><button className="rounded-lg border px-3 py-1 text-sm" onClick={()=>cmd("hiliteColor","transparent")}>Quitar resaltado</button></div>}
  {panel==="stickers"&&<div className="mt-2 rounded-xl border bg-card p-2"><div className="mb-2 flex gap-1 overflow-x-auto">{(Object.keys(STICKERS) as StickerGroup[]).map(g=><button key={g} className="rounded-full border px-2 py-1 text-xs" onClick={()=>setGroup(g)}>{g}</button>)}</div><div className="flex flex-wrap gap-1">{STICKERS[group].map((s,i)=><button key={i} className="h-9 w-9 text-xl" onClick={()=>cmd("insertText",s)}>{s}</button>)}</div></div>}
  {panel==="more"&&<div className="mt-2 flex flex-wrap gap-2 rounded-xl border bg-card p-2"><button className="rounded-lg border px-3 py-2" onClick={cut}><Scissors className="inline h-4 w-4"/> Cortar caja</button><button className="rounded-lg border px-3 py-2" onClick={()=>setCopied(refs.current[active]?.innerHTML??"")}><Copy className="inline h-4 w-4"/> Copiar</button><button className="rounded-lg border px-3 py-2" onClick={paste}>Pegar</button><button className="rounded-lg border px-3 py-2 text-destructive" onClick={removeSelectedImage}><Trash2 className="inline h-4 w-4"/> Quitar imagen seleccionada</button><button className="rounded-lg border px-3 py-2 text-destructive" onClick={()=>{const e=refs.current[active];if(e){e.innerHTML="";save(active)}}}><Trash2 className="inline h-4 w-4"/> Vaciar</button></div>}
  <div className="mt-1 text-xs text-muted-foreground">Editando: <b>{BOXES.find(b=>b.id===active)?.title}</b></div></div>
  <input ref={fileRef} type="file" accept="image/*" className="hidden" onChange={e=>{addImage(e.target.files?.[0]);e.currentTarget.value=""}}/>
  <div className="space-y-4">{BOXES.map(box=><section key={box.id} onPointerDown={()=>selectBase(box.id)} style={{backgroundColor:backgrounds[box.id]}} className={`planner-box-libre rounded-[1.4rem] border shadow-sm ${active===box.id?"border-[#D9A596]/60":"border-border"}`}><div className={`${box.tone} border-b border-border px-4 py-2 text-xs font-extrabold tracking-wide`}>{box.title}</div><div ref={el=>{refs.current[box.id]=el;if(el){upgradeImages(el);ensureRootHeight(el)}}} data-box-id={box.id} contentEditable suppressContentEditableWarning onFocus={()=>selectBase(box.id)} onInput={()=>{remember(box.id);save(box.id)}} onKeyUp={()=>remember(box.id)} onMouseUp={()=>remember(box.id)} onTouchEnd={()=>setTimeout(()=>remember(box.id),0)} onPointerDown={e=>startImageTransform(box.id,e)} onPointerMove={moveImage} onPointerUp={endImage} onPointerCancel={endImage} className="planner-box-libre-body relative min-h-[420px] px-4 py-4 text-base leading-7 outline-none empty:before:text-muted-foreground empty:before:content-[attr(data-placeholder)]" data-placeholder={box.placeholder}/></section>)}</div>
  <div style={{marginTop:"20px"}}><FlexibleNotes /></div>
 </PageShell>
}
function IconTool({children,title,onClick}:{children:React.ReactNode;title:string;onClick:()=>void}){return <button type="button" title={title} onMouseDown={e=>e.preventDefault()} onClick={onClick} className="grid h-11 w-11 place-items-center rounded-xl border bg-card shadow-sm [&_svg]:h-5 [&_svg]:w-5">{children}</button>}
