import { useEffect, useRef, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { Bold, CaseSensitive, Copy, Highlighter, ImagePlus, Italic, MoreHorizontal, Palette, Scissors, SmilePlus, Trash2, Underline } from "lucide-react";
import { AppGate } from "@/components/planner/AppGate";
import { PageShell } from "@/components/planner/PageShell";
import { FlexibleNotes } from "@/components/planner/FlexibleNotes";

export const Route = createFileRoute("/notas")({ component: () => <AppGate><NotasPage /></AppGate> });
type BoxId="hoy"|"prioridades"|"recordatorios"|"libre"; type Panel="stickers"|"colors"|"fonts"|"sizes"|"highlight"|"more"|null; type StickerGroup="Favoritos"|"Agenda"|"Deco"|"Comida"|"Viajes"|"Caritas";
const BOXES=[{id:"hoy" as BoxId,title:"HOY",tone:"bg-[#F7E5DF]",placeholder:"Tocá acá y escribí..."},{id:"prioridades" as BoxId,title:"PRIORIDADES",tone:"bg-[#F5E7D8]",placeholder:"Ideas, prioridades, listas..."},{id:"recordatorios" as BoxId,title:"RECORDATORIOS",tone:"bg-[#ECE6F3]",placeholder:"Cosas para no olvidar..."},{id:"libre" as BoxId,title:"LIENZO LIBRE",tone:"bg-[#F3E8E5]",placeholder:"Texto, imágenes, stickers..."}];
const STICKERS:Record<StickerGroup,string[]>={Favoritos:["⭐","❤️","✨","🌸","🦋","🌈","☀️","📌","💡","✅","🎯","📝"],Agenda:["📅","⏰","⏳","📌","📎","✏️","🖊️","📝","📚","💻","📞","💬","✅","❗","💡","🎯","💰","🛒"],Deco:["🎀","🌸","🌷","🌼","🌻","🌹","🍀","🌿","🍃","🦋","🐝","🌙","⭐","✨","💫","☁️","🌈","🕯️"],Comida:["☕","🫖","🍰","🎂","🍓","🍒","🍋","🍉","🥐","🍞","🥗","🍕","🍝","🍫","🍪","🥤","🍷","🧁"],Viajes:["✈️","🚗","🚲","🧳","🗺️","📍","🏖️","🏕️","🏨","🌊","⛰️","🌴","🎒","📷","🚆","🛳️","🌎","🧭"],Caritas:["😊","🥰","😍","🤩","😌","😂","😉","😎","🤗","🥳","😴","🤔","🙌","👏","💪","🙏","💖","💕"]};
const SIZES:[string,string][]=[["Muy chico","2"],["Chico","3"],["Normal","4"],["Grande","5"],["Muy grande","6"],["Enorme","7"]];
const COLORS=["#111111","#A84F4F","#D26A4C","#C48A2F","#66508D","#4F6E98","#B34F83","#4E7C72","#2F6F5F","#31708E"]; const HILITES=["#FFF3A3","#FFD9A0","#FFB3C1","#C9F2C7","#B8E3FF","#E3D1FF","#FFFFFF"]; const FONTS=["Arial","Verdana","Tahoma","Trebuchet MS","Georgia","Times New Roman","Courier New","Comic Sans MS","Segoe UI","Calibri","Garamond","Helvetica","Palatino","Century Gothic","Lucida Sans","Lucida Console","Book Antiqua","Impact","Consolas","Franklin Gothic Medium","Rockwell","Baskerville","Cambria","Candara"]; const storageKey=(id:BoxId)=>`planner-lienzo-${id}-v2`;
const handle=(corner:string)=>`<span class="resize-handle" data-resize="${corner}" style="position:absolute;width:14px;height:14px;border:2px solid #fff;background:#63a7d8;border-radius:50%;z-index:4;${corner.includes("n")?"top:-8px;":"bottom:-8px;"}${corner.includes("w")?"left:-8px;":"right:-8px;"}"></span>`;
const freeImageHtml=(src:string)=>`<span class="planner-free-image" contenteditable="false" data-selected="true" style="position:absolute;left:16px;top:16px;width:45%;max-width:calc(100% - 32px);display:block;z-index:2;touch-action:none;user-select:none;"><img src="${src}" alt="Imagen" draggable="false" style="display:block;width:100%;height:auto;border-radius:10px;pointer-events:auto;"/>${handle("nw")}${handle("ne")}${handle("sw")}${handle("se")}</span>`;
function upgradeImages(root:HTMLElement){root.querySelectorAll<HTMLImageElement>("img").forEach(img=>{if(img.closest(".planner-free-image"))return;const wrap=document.createElement("span");wrap.innerHTML=freeImageHtml(img.src);img.replaceWith(wrap.firstElementChild!);});}
function ensureRootHeight(root:HTMLElement){let bottom=192;root.querySelectorAll<HTMLElement>(".planner-free-image").forEach(w=>{const top=parseFloat(w.style.top)||0;const width=w.getBoundingClientRect().width||parseFloat(w.style.width)||120;const img=w.querySelector("img") as HTMLImageElement|null;const ratio=img?.naturalWidth&&img?.naturalHeight?img.naturalWidth/img.naturalHeight:1;bottom=Math.max(bottom,top+width/Math.max(ratio,.1)+28)});root.style.minHeight=`${Math.ceil(bottom)}px`;}

function NotasPage(){
 const refs=useRef<Record<BoxId,HTMLDivElement|null>>({hoy:null,prioridades:null,recordatorios:null,libre:null}); const fileRef=useRef<HTMLInputElement>(null); const selectionRef=useRef<Range|null>(null); const transformRef=useRef<{box:BoxId;wrap:HTMLElement;root:HTMLElement;mode:"move"|"resize";corner:string;x:number;y:number;left:number;top:number;width:number;ratio:number}|null>(null); const [active,setActive]=useState<BoxId>("hoy"); const [panel,setPanel]=useState<Panel>(null); const [group,setGroup]=useState<StickerGroup>("Favoritos"); const [copied,setCopied]=useState("");
 useEffect(()=>{BOXES.forEach(({id})=>{const el=refs.current[id];if(el){el.innerHTML=localStorage.getItem(storageKey(id))??"";upgradeImages(el);ensureRootHeight(el);localStorage.setItem(storageKey(id),el.innerHTML)}})},[]);
 const save=(id:BoxId)=>{const el=refs.current[id];if(el)localStorage.setItem(storageKey(id),el.innerHTML)}; const remember=()=>{const s=window.getSelection();if(s&&s.rangeCount&&refs.current[active]?.contains(s.anchorNode))selectionRef.current=s.getRangeAt(0).cloneRange()}; const focus=()=>{refs.current[active]?.focus();const r=selectionRef.current,s=window.getSelection();if(r&&s){s.removeAllRanges();s.addRange(r)}}; const cmd=(c:string,v?:string)=>{const flexId=document.body.dataset.activeFlexNoteId;if(flexId){window.dispatchEvent(new CustomEvent("planner:flex-format",{detail:{command:c,value:v}}));return;}focus();document.execCommand(c,false,v);remember();save(active)};
 const selectBase=(id:BoxId)=>{delete document.body.dataset.activeFlexNoteId;setActive(id)};
 const addImage=(file?:File)=>{if(!file)return;const r=new FileReader();r.onload=()=>{const src=String(r.result);const flexId=document.body.dataset.activeFlexNoteId;if(flexId){window.dispatchEvent(new CustomEvent("planner:flex-add-image",{detail:{noteId:flexId,src}}));return;}const root=refs.current[active];if(!root)return;root.querySelectorAll<HTMLElement>(".planner-free-image").forEach(w=>w.dataset.selected="false");root.insertAdjacentHTML("beforeend",freeImageHtml(src));ensureRootHeight(root);save(active)};r.readAsDataURL(file)};
 const startImageTransform=(box:BoxId,e:React.PointerEvent<HTMLDivElement>)=>{selectBase(box);const target=e.target as HTMLElement;const wrap=target.closest<HTMLElement>(".planner-free-image");const root=refs.current[box];if(!wrap||!root)return;e.preventDefault();e.stopPropagation();root.querySelectorAll<HTMLElement>(".planner-free-image").forEach(w=>w.dataset.selected=String(w===wrap));const rect=wrap.getBoundingClientRect(),img=wrap.querySelector("img") as HTMLImageElement|null;transformRef.current={box,wrap,root,mode:target.dataset.resize?"resize":"move",corner:target.dataset.resize||"",x:e.clientX,y:e.clientY,left:parseFloat(wrap.style.left)||0,top:parseFloat(wrap.style.top)||0,width:rect.width,ratio:img?.naturalWidth&&img?.naturalHeight?img.naturalWidth/img.naturalHeight:rect.width/Math.max(rect.height,1)};target.setPointerCapture?.(e.pointerId)};
 const moveImage=(e:React.PointerEvent<HTMLDivElement>)=>{const t=transformRef.current;if(!t)return;e.preventDefault();const dx=e.clientX-t.x,dy=e.clientY-t.y,rootW=t.root.clientWidth;if(t.mode==="move"){const h=t.width/t.ratio;t.wrap.style.left=`${Math.max(0,Math.min(rootW-t.width,t.left+dx))}px`;t.wrap.style.top=`${Math.max(0,t.top+dy)}px`;t.root.style.minHeight=`${Math.max(192,Math.ceil((parseFloat(t.wrap.style.top)||0)+h+28))}px`;}else{const west=t.corner.includes("w"),north=t.corner.includes("n");const width=Math.max(70,Math.min(Math.max(90,rootW-8),t.width+(west?-dx:dx)));let left=west?t.left+(t.width-width):t.left;let top=north?t.top+(t.width-width)/t.ratio:t.top;left=Math.max(0,Math.min(rootW-width,left));top=Math.max(0,top);t.wrap.style.width=`${width}px`;t.wrap.style.left=`${left}px`;t.wrap.style.top=`${top}px`;t.root.style.minHeight=`${Math.max(192,Math.ceil(top+width/t.ratio+28))}px`;}};
 const endImage=()=>{const t=transformRef.current;if(!t)return;ensureRootHeight(t.root);save(t.box);transformRef.current=null};
 const cut=()=>{const e=refs.current[active];if(e){setCopied(e.innerHTML);e.innerHTML="";save(active)}}; const paste=()=>{const e=refs.current[active];if(e&&copied){e.insertAdjacentHTML("beforeend",copied);ensureRootHeight(e);save(active)}};
 return <PageShell title="Notas" subtitle="Tocá una hoja y empezá. Las herramientas aparecen cuando las necesitás.">
  <style>{`.planner-free-image[data-selected="true"]{outline:2px solid #63a7d8;outline-offset:2px}.planner-free-image .resize-handle{display:none}.planner-free-image[data-selected="true"] .resize-handle{display:block}.planner-free-image[data-selected="true"] img{cursor:move}.resize-handle[data-resize="nw"],.resize-handle[data-resize="se"]{cursor:nwse-resize}.resize-handle[data-resize="ne"],.resize-handle[data-resize="sw"]{cursor:nesw-resize}@media print{.planner-free-image{outline:none!important}.resize-handle{display:none!important}}`}</style>
  <div className="sticky top-0 z-30 -mx-4 mb-4 border-y border-border bg-background/95 px-4 py-2 backdrop-blur"><div className="flex flex-wrap items-center gap-1.5"><IconTool title="Negrita" onClick={()=>cmd("bold")}><Bold/></IconTool><IconTool title="Cursiva" onClick={()=>cmd("italic")}><Italic/></IconTool><IconTool title="Subrayar" onClick={()=>cmd("underline")}><Underline/></IconTool><IconTool title="Fuente" onClick={()=>{if(document.body.dataset.activeFlexNoteId)window.dispatchEvent(new CustomEvent("planner:flex-save"));setPanel(panel==="fonts"?null:"fonts")}}><CaseSensitive/></IconTool><IconTool title="Tamaño" onClick={()=>{if(document.body.dataset.activeFlexNoteId)window.dispatchEvent(new CustomEvent("planner:flex-save"));setPanel(panel==="sizes"?null:"sizes")}}><span className="text-xs font-black">Aa</span></IconTool><IconTool title="Imagen" onClick={()=>fileRef.current?.click()}><ImagePlus/></IconTool><IconTool title="Stickers" onClick={()=>setPanel(panel==="stickers"?null:"stickers")}><SmilePlus/></IconTool><IconTool title="Color" onClick={()=>{if(document.body.dataset.activeFlexNoteId)window.dispatchEvent(new CustomEvent("planner:flex-save"));setPanel(panel==="colors"?null:"colors")}}><Palette/></IconTool><IconTool title="Resaltador" onClick={()=>{if(document.body.dataset.activeFlexNoteId)window.dispatchEvent(new CustomEvent("planner:flex-save"));setPanel(panel==="highlight"?null:"highlight")}}><Highlighter/></IconTool><IconTool title="Más" onClick={()=>setPanel(panel==="more"?null:"more")}><MoreHorizontal/></IconTool></div>
  {panel==="fonts"&&<div className="mt-2 rounded-xl border bg-card p-2"><select className="h-11 w-full rounded-lg border bg-background px-2" defaultValue="" onChange={e=>{if(e.target.value)cmd("fontName",e.target.value);e.target.value=""}}><option value="" disabled>Elegí una fuente…</option>{FONTS.map(f=><option key={f} value={f} style={{fontFamily:f}}>{f}</option>)}</select></div>}
  {panel==="sizes"&&<div className="mt-2 rounded-xl border bg-card p-2"><select className="h-11 w-full rounded-lg border bg-background px-2" defaultValue="" onChange={e=>{if(e.target.value)cmd("fontSize",e.target.value);e.target.value=""}}><option value="" disabled>Elegí un tamaño…</option>{SIZES.map(([label,v])=><option key={v} value={v}>{label}</option>)}</select></div>}
  {panel==="colors"&&<div className="mt-2 flex flex-wrap items-center gap-2 rounded-xl border bg-card p-2">{COLORS.map(c=><button key={c} className="h-8 w-8 rounded-full border" style={{backgroundColor:c}} onClick={()=>cmd("foreColor",c)}/>)}<label className="flex h-8 w-8 cursor-pointer items-center justify-center rounded-full border" title="Elegir cualquier color" style={{background:"conic-gradient(red,yellow,lime,cyan,blue,magenta,red)"}}><input type="color" className="h-0 w-0 opacity-0" onChange={e=>cmd("foreColor",e.target.value)}/></label></div>}
  {panel==="highlight"&&<div className="mt-2 flex flex-wrap items-center gap-2 rounded-xl border bg-card p-2">{HILITES.map(c=><button key={c} className="h-8 w-8 rounded-full border" style={{backgroundColor:c}} onClick={()=>cmd("hiliteColor",c)}/>)}<label className="flex h-8 w-8 cursor-pointer items-center justify-center rounded-full border" title="Elegir cualquier color" style={{background:"conic-gradient(red,yellow,lime,cyan,blue,magenta,red)"}}><input type="color" className="h-0 w-0 opacity-0" onChange={e=>cmd("hiliteColor",e.target.value)}/></label><button className="rounded-lg border px-3 py-1 text-sm" onClick={()=>cmd("hiliteColor","transparent")}>Quitar resaltado</button></div>}
  {panel==="stickers"&&<div className="mt-2 rounded-xl border bg-card p-2"><div className="mb-2 flex gap-1 overflow-x-auto">{(Object.keys(STICKERS) as StickerGroup[]).map(g=><button key={g} className="rounded-full border px-2 py-1 text-xs" onClick={()=>setGroup(g)}>{g}</button>)}</div><div className="flex flex-wrap gap-1">{STICKERS[group].map((s,i)=><button key={i} className="h-9 w-9 text-xl" onClick={()=>cmd("insertText",s)}>{s}</button>)}</div></div>}
  {panel==="more"&&<div className="mt-2 flex gap-2 rounded-xl border bg-card p-2"><button className="rounded-lg border px-3 py-2" onClick={cut}><Scissors className="inline h-4 w-4"/> Cortar caja</button><button className="rounded-lg border px-3 py-2" onClick={()=>setCopied(refs.current[active]?.innerHTML??"")}><Copy className="inline h-4 w-4"/> Copiar</button><button className="rounded-lg border px-3 py-2" onClick={paste}>Pegar</button><button className="rounded-lg border px-3 py-2 text-destructive" onClick={()=>{const e=refs.current[active];if(e){e.innerHTML="";save(active)}}}><Trash2 className="inline h-4 w-4"/> Vaciar</button></div>}
  <div className="mt-1 text-xs text-muted-foreground">Editando: <b>{BOXES.find(b=>b.id===active)?.title}</b></div></div>
  <input ref={fileRef} type="file" accept="image/*" className="hidden" onChange={e=>{addImage(e.target.files?.[0]);e.currentTarget.value=""}}/>
  <div className="space-y-4">{BOXES.map(box=><section key={box.id} onPointerDown={()=>selectBase(box.id)} className={`overflow-hidden rounded-[1.4rem] border bg-card shadow-sm ${active===box.id?"ring-2 ring-[#D9A596]/35 border-[#D9A596]":"border-border"}`}><div className={`${box.tone} border-b border-border px-4 py-2 text-xs font-extrabold tracking-wide`}>{box.title}</div><div ref={el=>{refs.current[box.id]=el;if(el){upgradeImages(el);ensureRootHeight(el)}}} contentEditable suppressContentEditableWarning onFocus={()=>selectBase(box.id)} onInput={()=>{remember();save(box.id)}} onKeyUp={remember} onMouseUp={remember} onPointerDown={e=>startImageTransform(box.id,e)} onPointerMove={moveImage} onPointerUp={endImage} onPointerCancel={endImage} className="relative min-h-48 overflow-hidden px-4 py-4 text-base leading-7 outline-none empty:before:text-muted-foreground empty:before:content-[attr(data-placeholder)]" data-placeholder={box.placeholder}/></section>)}</div>
  <FlexibleNotes />
 </PageShell>
}
function IconTool({children,title,onClick}:{children:React.ReactNode;title:string;onClick:()=>void}){return <button type="button" title={title} onMouseDown={e=>e.preventDefault()} onClick={onClick} className="grid h-11 w-11 place-items-center rounded-xl border bg-card shadow-sm [&_svg]:h-5 [&_svg]:w-5">{children}</button>}
