import { useRef } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { Download,Upload,ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { AppGate } from "@/components/planner/AppGate";
import { PageShell } from "@/components/planner/PageShell";
import { Button } from "@/components/ui/button";
import { usePlanner } from "@/lib/planner/store";
import { useLanguage } from "@/lib/language";
export const Route=createFileRoute("/respaldo")({component:()=> <AppGate><Backup/></AppGate>});
function Backup(){const{state,replaceState}=usePlanner();const{lang}=useLanguage();const input=useRef<HTMLInputElement>(null);
 const download=()=>{const extra:Object=Object.fromEntries(Object.keys(localStorage).filter(k=>k.startsWith("planner-")).map(k=>[k,localStorage.getItem(k)]));const blob=new Blob([JSON.stringify({version:1,date:new Date().toISOString(),state,local:extra},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`mi-planner-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};
 const restore=(f?:File)=>{if(!f)return;const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(String(r.result));if(!data.state)throw new Error();replaceState(data.state);if(data.local)Object.entries(data.local).forEach(([k,v])=>{if(typeof v==="string")localStorage.setItem(k,v)});toast.success(lang==="en"?"Backup restored":"Copia restaurada");setTimeout(()=>location.reload(),500)}catch{toast.error(lang==="en"?"Invalid backup file":"El archivo de copia no es válido")}};r.readAsText(f)};
 return <PageShell title={lang==="en"?"Backup":"Copia de seguridad"} subtitle={lang==="en"?"Keep an extra copy of your planner":"Guardá una copia extra de tu planner"}><section className="card-soft p-5"><ShieldCheck className="mb-3 h-8 w-8 text-olive"/><h2 className="font-bold">{lang==="en"?"Download a complete copy":"Descargar una copia completa"}</h2><p className="mt-1 text-sm text-muted-foreground">{lang==="en"?"Includes planner data and locally saved notes.":"Incluye los datos del planner y las notas guardadas localmente."}</p><Button className="mt-4 w-full" onClick={download}><Download className="h-4 w-4"/>{lang==="en"?"Download backup":"Descargar copia"}</Button></section><section className="card-soft mt-4 p-5"><h2 className="font-bold">{lang==="en"?"Restore a copy":"Restaurar una copia"}</h2><p className="mt-1 text-sm text-muted-foreground">{lang==="en"?"Choose a backup file previously downloaded from Mi Planner.":"Elegí un archivo de copia descargado anteriormente desde Mi Planner."}</p><input ref={input} type="file" accept="application/json,.json" className="hidden" onChange={e=>restore(e.target.files?.[0])}/><Button variant="outline" className="mt-4 w-full" onClick={()=>input.current?.click()}><Upload className="h-4 w-4"/>{lang==="en"?"Choose backup":"Elegir copia"}</Button></section></PageShell>}
