/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AsistenteRouteImport } from './routes/asistente'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as ComprasRouteImport } from './routes/compras'
import { Route as CuentaRouteImport } from './routes/cuenta'
import { Route as ImprimirRouteImport } from './routes/imprimir'
import { Route as MasRouteImport } from './routes/mas'
import { Route as NotasRouteImport } from './routes/notas'
import { Route as NotasFechaRouteImport } from './routes/notas-fecha'
import { Route as PersonalizarRouteImport } from './routes/personalizar'
import { Route as ProyectosRouteImport } from './routes/proyectos'
import { Route as RespaldoRouteImport } from './routes/respaldo'
import { Route as TareasRouteImport } from './routes/tareas'
import { Route as SeccionIdRouteImport } from './routes/seccion.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AsistenteRoute = AsistenteRouteImport.update({
  id: '/asistente',
  path: '/asistente',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasRoute = ComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentaRoute = CuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprimirRoute = ImprimirRouteImport.update({
  id: '/imprimir',
  path: '/imprimir',
  getParentRoute: () => rootRouteImport,
} as any)
const MasRoute = MasRouteImport.update({
  id: '/mas',
  path: '/mas',
  getParentRoute: () => rootRouteImport,
} as any)
const NotasRoute = NotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => rootRouteImport,
} as any)
const NotasFechaRoute = NotasFechaRouteImport.update({
  id: '/notas-fecha',
  path: '/notas-fecha',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalizarRoute = PersonalizarRouteImport.update({
  id: '/personalizar',
  path: '/personalizar',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosRoute = ProyectosRouteImport.update({
  id: '/proyectos',
  path: '/proyectos',
  getParentRoute: () => rootRouteImport,
} as any)
const RespaldoRoute = RespaldoRouteImport.update({
  id: '/respaldo',
  path: '/respaldo',
  getParentRoute: () => rootRouteImport,
} as any)
const TareasRoute = TareasRouteImport.update({
  id: '/tareas',
  path: '/tareas',
  getParentRoute: () => rootRouteImport,
} as any)
const SeccionIdRoute = SeccionIdRouteImport.update({
  id: '/seccion/$id',
  path: '/seccion/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asistente': typeof AsistenteRoute
  '/buscar': typeof BuscarRoute
  '/calendario': typeof CalendarioRoute
  '/compras': typeof ComprasRoute
  '/cuenta': typeof CuentaRoute
  '/imprimir': typeof ImprimirRoute
  '/mas': typeof MasRoute
  '/notas': typeof NotasRoute
  '/notas-fecha': typeof NotasFechaRoute
  '/personalizar': typeof PersonalizarRoute
  '/proyectos': typeof ProyectosRoute
  '/respaldo': typeof RespaldoRoute
  '/tareas': typeof TareasRoute
  '/seccion/$id': typeof SeccionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asistente': typeof AsistenteRoute
  '/buscar': typeof BuscarRoute
  '/calendario': typeof CalendarioRoute
  '/compras': typeof ComprasRoute
  '/cuenta': typeof CuentaRoute
  '/imprimir': typeof ImprimirRoute
  '/mas': typeof MasRoute
  '/notas': typeof NotasRoute
  '/notas-fecha': typeof NotasFechaRoute
  '/personalizar': typeof PersonalizarRoute
  '/proyectos': typeof ProyectosRoute
  '/respaldo': typeof RespaldoRoute
  '/tareas': typeof TareasRoute
  '/seccion/$id': typeof SeccionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asistente': typeof AsistenteRoute
  '/buscar': typeof BuscarRoute
  '/calendario': typeof CalendarioRoute
  '/compras': typeof ComprasRoute
  '/cuenta': typeof CuentaRoute
  '/imprimir': typeof ImprimirRoute
  '/mas': typeof MasRoute
  '/notas': typeof NotasRoute
  '/notas-fecha': typeof NotasFechaRoute
  '/personalizar': typeof PersonalizarRoute
  '/proyectos': typeof ProyectosRoute
  '/respaldo': typeof RespaldoRoute
  '/tareas': typeof TareasRoute
  '/seccion/$id': typeof SeccionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/asistente'
    | '/buscar'
    | '/calendario'
    | '/compras'
    | '/cuenta'
    | '/imprimir'
    | '/mas'
    | '/notas'
    | '/notas-fecha'
    | '/personalizar'
    | '/proyectos'
    | '/respaldo'
    | '/tareas'
    | '/seccion/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/asistente'
    | '/buscar'
    | '/calendario'
    | '/compras'
    | '/cuenta'
    | '/imprimir'
    | '/mas'
    | '/notas'
    | '/notas-fecha'
    | '/personalizar'
    | '/proyectos'
    | '/respaldo'
    | '/tareas'
    | '/seccion/$id'
  id:
    | '__root__'
    | '/'
    | '/asistente'
    | '/buscar'
    | '/calendario'
    | '/compras'
    | '/cuenta'
    | '/imprimir'
    | '/mas'
    | '/notas'
    | '/notas-fecha'
    | '/personalizar'
    | '/proyectos'
    | '/respaldo'
    | '/tareas'
    | '/seccion/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AsistenteRoute: typeof AsistenteRoute
  BuscarRoute: typeof BuscarRoute
  CalendarioRoute: typeof CalendarioRoute
  ComprasRoute: typeof ComprasRoute
  CuentaRoute: typeof CuentaRoute
  ImprimirRoute: typeof ImprimirRoute
  MasRoute: typeof MasRoute
  NotasRoute: typeof NotasRoute
  NotasFechaRoute: typeof NotasFechaRoute
  PersonalizarRoute: typeof PersonalizarRoute
  ProyectosRoute: typeof ProyectosRoute
  RespaldoRoute: typeof RespaldoRoute
  TareasRoute: typeof TareasRoute
  SeccionIdRoute: typeof SeccionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asistente': {
      id: '/asistente'
      path: '/asistente'
      fullPath: '/asistente'
      preLoaderRoute: typeof AsistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras': {
      id: '/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof ComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuenta': {
      id: '/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof CuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprimir': {
      id: '/imprimir'
      path: '/imprimir'
      fullPath: '/imprimir'
      preLoaderRoute: typeof ImprimirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mas': {
      id: '/mas'
      path: '/mas'
      fullPath: '/mas'
      preLoaderRoute: typeof MasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notas': {
      id: '/notas'
      path: '/notas'
      fullPath: '/notas'
      preLoaderRoute: typeof NotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notas-fecha': {
      id: '/notas-fecha'
      path: '/notas-fecha'
      fullPath: '/notas-fecha'
      preLoaderRoute: typeof NotasFechaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personalizar': {
      id: '/personalizar'
      path: '/personalizar'
      fullPath: '/personalizar'
      preLoaderRoute: typeof PersonalizarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos': {
      id: '/proyectos'
      path: '/proyectos'
      fullPath: '/proyectos'
      preLoaderRoute: typeof ProyectosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/respaldo': {
      id: '/respaldo'
      path: '/respaldo'
      fullPath: '/respaldo'
      preLoaderRoute: typeof RespaldoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tareas': {
      id: '/tareas'
      path: '/tareas'
      fullPath: '/tareas'
      preLoaderRoute: typeof TareasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seccion/$id': {
      id: '/seccion/$id'
      path: '/seccion/$id'
      fullPath: '/seccion/$id'
      preLoaderRoute: typeof SeccionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AsistenteRoute: AsistenteRoute,
  BuscarRoute: BuscarRoute,
  CalendarioRoute: CalendarioRoute,
  ComprasRoute: ComprasRoute,
  CuentaRoute: CuentaRoute,
  ImprimirRoute: ImprimirRoute,
  MasRoute: MasRoute,
  NotasRoute: NotasRoute,
  NotasFechaRoute: NotasFechaRoute,
  PersonalizarRoute: PersonalizarRoute,
  ProyectosRoute: ProyectosRoute,
  RespaldoRoute: RespaldoRoute,
  TareasRoute: TareasRoute,
  SeccionIdRoute: SeccionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
