/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AsistenteRouteImport } from './routes/asistente'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as MasRouteImport } from './routes/mas'
import { Route as NotasRouteImport } from './routes/notas'
import { Route as PersonalizarRouteImport } from './routes/personalizar'
import { Route as ProyectosRouteImport } from './routes/proyectos'
import { Route as TareasRouteImport } from './routes/tareas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AsistenteRoute = AsistenteRouteImport.update({
  id: '/asistente',
  path: '/asistente',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const MasRoute = MasRouteImport.update({
  id: '/mas',
  path: '/mas',
  getParentRoute: () => rootRouteImport,
} as any)
const NotasRoute = NotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalizarRoute = PersonalizarRouteImport.update({
  id: '/personalizar',
  path: '/personalizar',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosRoute = ProyectosRouteImport.update({
  id: '/proyectos',
  path: '/proyectos',
  getParentRoute: () => rootRouteImport,
} as any)
const TareasRoute = TareasRouteImport.update({
  id: '/tareas',
  path: '/tareas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asistente': typeof AsistenteRoute
  '/calendario': typeof CalendarioRoute
  '/mas': typeof MasRoute
  '/notas': typeof NotasRoute
  '/personalizar': typeof PersonalizarRoute
  '/proyectos': typeof ProyectosRoute
  '/tareas': typeof TareasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asistente': typeof AsistenteRoute
  '/calendario': typeof CalendarioRoute
  '/mas': typeof MasRoute
  '/notas': typeof NotasRoute
  '/personalizar': typeof PersonalizarRoute
  '/proyectos': typeof ProyectosRoute
  '/tareas': typeof TareasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asistente': typeof AsistenteRoute
  '/calendario': typeof CalendarioRoute
  '/mas': typeof MasRoute
  '/notas': typeof NotasRoute
  '/personalizar': typeof PersonalizarRoute
  '/proyectos': typeof ProyectosRoute
  '/tareas': typeof TareasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/asistente'
    | '/calendario'
    | '/mas'
    | '/notas'
    | '/personalizar'
    | '/proyectos'
    | '/tareas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/asistente'
    | '/calendario'
    | '/mas'
    | '/notas'
    | '/personalizar'
    | '/proyectos'
    | '/tareas'
  id:
    | '__root__'
    | '/'
    | '/asistente'
    | '/calendario'
    | '/mas'
    | '/notas'
    | '/personalizar'
    | '/proyectos'
    | '/tareas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AsistenteRoute: typeof AsistenteRoute
  CalendarioRoute: typeof CalendarioRoute
  MasRoute: typeof MasRoute
  NotasRoute: typeof NotasRoute
  PersonalizarRoute: typeof PersonalizarRoute
  ProyectosRoute: typeof ProyectosRoute
  TareasRoute: typeof TareasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asistente': {
      id: '/asistente'
      path: '/asistente'
      fullPath: '/asistente'
      preLoaderRoute: typeof AsistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mas': {
      id: '/mas'
      path: '/mas'
      fullPath: '/mas'
      preLoaderRoute: typeof MasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notas': {
      id: '/notas'
      path: '/notas'
      fullPath: '/notas'
      preLoaderRoute: typeof NotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personalizar': {
      id: '/personalizar'
      path: '/personalizar'
      fullPath: '/personalizar'
      preLoaderRoute: typeof PersonalizarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos': {
      id: '/proyectos'
      path: '/proyectos'
      fullPath: '/proyectos'
      preLoaderRoute: typeof ProyectosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tareas': {
      id: '/tareas'
      path: '/tareas'
      fullPath: '/tareas'
      preLoaderRoute: typeof TareasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AsistenteRoute: AsistenteRoute,
  CalendarioRoute: CalendarioRoute,
  MasRoute: MasRoute,
  NotasRoute: NotasRoute,
  PersonalizarRoute: PersonalizarRoute,
  ProyectosRoute: ProyectosRoute,
  TareasRoute: TareasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
